export interface AIEntry {
  id: string
  name: string
  category: string
  description: string
  platform: string
  region: string
  accessType: "Free" | "Freemium" | "Paid"
  pricing: string
  tags: string[]
  popularity: number
  lastUpdated: string
  isTrending?: boolean
}

export const aiEntries: AIEntry[] = [
  {
    id: "1",
    name: "GPT-4",
    category: "Generative AI",
    description: "Advanced language model for text generation, reasoning, and complex tasks.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$20/month",
    tags: ["language-model", "generative", "api"],
    popularity: 98,
    lastUpdated: "2025-11-10",
    isTrending: true,
  },
  {
    id: "35",
    name: "GPT-3.5",
    category: "Generative AI",
    description: "OpenAI's efficient language model, predecessor to GPT-4.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "api"],
    popularity: 92,
    lastUpdated: "2025-11-14",
  },
  {
    id: "36",
    name: "GPT-3",
    category: "Generative AI",
    description: "OpenAI's breakthrough 175B parameter language model.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "api"],
    popularity: 88,
    lastUpdated: "2025-11-14",
  },
  {
    id: "37",
    name: "GPT-2",
    category: "Generative AI",
    description: "OpenAI's 1.5B parameter model, open-sourced for research.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "generative", "open-source"],
    popularity: 75,
    lastUpdated: "2025-11-14",
  },
  {
    id: "38",
    name: "GPT-1",
    category: "Generative AI",
    description: "OpenAI's first generative pre-trained transformer model.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "generative", "research"],
    popularity: 65,
    lastUpdated: "2025-11-14",
  },
  {
    id: "2",
    name: "Claude 3",
    category: "Generative AI",
    description: "Anthropic's latest Claude family with Opus, Sonnet, and Haiku variants.",
    platform: "https://claude.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $20/month Pro",
    tags: ["language-model", "generative", "safe-ai", "constitutional-ai"],
    popularity: 95,
    lastUpdated: "2025-11-14",
    isTrending: true,
  },
  {
    id: "39",
    name: "Claude 2",
    category: "Generative AI",
    description: "Anthropic's second-generation constitutional AI model with improved capabilities.",
    platform: "https://claude.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "generative", "safe-ai"],
    popularity: 90,
    lastUpdated: "2025-11-14",
  },
  {
    id: "40",
    name: "Claude 1",
    category: "Generative AI",
    description: "Anthropic's first constitutional AI model focused on safety.",
    platform: "https://claude.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "safe-ai"],
    popularity: 82,
    lastUpdated: "2025-11-14",
  },
  {
    id: "3",
    name: "Midjourney",
    category: "Computer Vision",
    description: "AI image generation based on text prompts with exceptional artistic quality.",
    platform: "https://midjourney.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$10-120/month",
    tags: ["image-generation", "art", "design"],
    popularity: 92,
    lastUpdated: "2025-11-08",
    isTrending: true,
  },
  {
    id: "4",
    name: "DALL-E 3",
    category: "Computer Vision",
    description: "OpenAI image generation model creating realistic images from descriptions.",
    platform: "https://openai.com/dall-e-3",
    region: "USA",
    accessType: "Paid",
    pricing: "$0.02-0.04 per image",
    tags: ["image-generation", "vision", "api"],
    popularity: 90,
    lastUpdated: "2025-11-07",
  },
  {
    id: "5",
    name: "Whisper",
    category: "NLP/Audio",
    description: "Speech-to-text model supporting 99 languages with high accuracy.",
    platform: "https://openai.com/research/whisper",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["speech-to-text", "nlp", "audio"],
    popularity: 88,
    lastUpdated: "2025-11-06",
  },
  {
    id: "6",
    name: "YOLO v8",
    category: "Computer Vision",
    description: "State-of-the-art object detection model for real-time applications.",
    platform: "https://ultralytics.com",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["object-detection", "vision", "real-time"],
    popularity: 87,
    lastUpdated: "2025-11-05",
  },
  {
    id: "7",
    name: "Stable Diffusion",
    category: "Computer Vision",
    description: "Open-source image generation model with customizable parameters.",
    platform: "https://huggingface.co/stabilityai",
    region: "EU",
    accessType: "Free",
    pricing: "Open source",
    tags: ["image-generation", "open-source", "diffusion"],
    popularity: 89,
    lastUpdated: "2025-11-04",
  },
  {
    id: "8",
    name: "Hugging Face",
    category: "Multimodal Platform",
    description: "Hub for thousands of pre-trained AI models, datasets, and tools.",
    platform: "https://huggingface.co",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["platform", "models", "nlp", "vision"],
    popularity: 91,
    lastUpdated: "2025-11-03",
  },
  {
    id: "9",
    name: "LLaMA 3.1",
    category: "Generative AI",
    description: "Meta's latest open-source LLM with up to 405B parameters and extended capabilities.",
    platform: "https://ai.meta.com/llama/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "llm"],
    popularity: 89,
    lastUpdated: "2025-11-14",
    isTrending: true,
  },
  {
    id: "44",
    name: "LLaMA 3",
    category: "Generative AI",
    description: "Meta's third-generation open-source language model with improved performance.",
    platform: "https://ai.meta.com/llama/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "llm"],
    popularity: 88,
    lastUpdated: "2025-11-14",
  },
  {
    id: "45",
    name: "LLaMA 2",
    category: "Generative AI",
    description: "Meta's second-generation open-source LLM with commercial licensing.",
    platform: "https://ai.meta.com/llama/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "llm"],
    popularity: 86,
    lastUpdated: "2025-11-14",
  },
  {
    id: "46",
    name: "LLaMA 1",
    category: "Generative AI",
    description: "Meta's first-generation open-source large language model.",
    platform: "https://ai.meta.com/llama/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "research"],
    popularity: 80,
    lastUpdated: "2025-11-14",
  },
  {
    id: "10",
    name: "Gemini 1.5",
    category: "Generative AI",
    description: "Google's latest multimodal AI with extended context window and enhanced capabilities.",
    platform: "https://gemini.google.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $20/month Pro",
    tags: ["language-model", "multimodal", "generative", "long-context"],
    popularity: 94,
    lastUpdated: "2025-11-14",
    isTrending: true,
  },
  {
    id: "41",
    name: "Gemini 1",
    category: "Generative AI",
    description: "Google's first-generation multimodal AI model processing text, images, and code.",
    platform: "https://gemini.google.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "multimodal", "generative"],
    popularity: 91,
    lastUpdated: "2025-11-14",
  },
  {
    id: "42",
    name: "PaLM-2",
    category: "Generative AI",
    description: "Google's second-generation Pathways Language Model with improved reasoning.",
    platform: "https://ai.google/discover/palm2",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "reasoning"],
    popularity: 87,
    lastUpdated: "2025-11-14",
  },
  {
    id: "43",
    name: "PaLM",
    category: "Generative AI",
    description: "Google's Pathways Language Model with 540B parameters.",
    platform: "https://ai.google",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "research"],
    popularity: 83,
    lastUpdated: "2025-11-14",
  },
  {
    id: "11",
    name: "Runway",
    category: "Generative AI",
    description: "AI creative platform for video generation, editing, and visual effects.",
    platform: "https://runwayml.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $12-96/month",
    tags: ["video", "generative", "creative"],
    popularity: 85,
    lastUpdated: "2025-10-31",
    isTrending: true,
  },
  {
    id: "12",
    name: "ElevenLabs",
    category: "Audio/NLP",
    description: "Text-to-speech AI with natural sounding voices in 29+ languages.",
    platform: "https://elevenlabs.io",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + $11-99/month",
    tags: ["text-to-speech", "audio", "voice"],
    popularity: 84,
    lastUpdated: "2025-10-30",
  },
  {
    id: "13",
    name: "Copilot",
    category: "Code Generation",
    description: "AI code completion and generation assistant by GitHub.",
    platform: "https://github.com/features/copilot",
    region: "USA",
    accessType: "Paid",
    pricing: "$10/month individual",
    tags: ["code-generation", "programming", "developer-tools"],
    popularity: 93,
    lastUpdated: "2025-10-29",
  },
  {
    id: "14",
    name: "Synthesia",
    category: "Video Generation",
    description: "AI video generation platform with avatars and multi-language support.",
    platform: "https://www.synthesia.io",
    region: "EU",
    accessType: "Paid",
    pricing: "$30-480/month",
    tags: ["video", "avatar", "generative"],
    popularity: 82,
    lastUpdated: "2025-10-28",
  },
  {
    id: "15",
    name: "Perplexity AI",
    category: "Search/QA",
    description: "AI-powered search engine with real-time information and citations.",
    platform: "https://www.perplexity.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $20/month Pro",
    tags: ["search", "qa", "information-retrieval"],
    popularity: 83,
    lastUpdated: "2025-10-27",
  },
  {
    id: "16",
    name: "AutoGPT",
    category: "Autonomous AI",
    description: "Autonomous AI agent capable of completing complex tasks independently.",
    platform: "https://agentgpt.reworkd.ai",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["autonomous", "agent", "automation"],
    popularity: 81,
    lastUpdated: "2025-10-26",
  },
  {
    id: "17",
    name: "Descript",
    category: "Audio/Video Processing",
    description: "AI-powered video and podcast editing platform with transcription.",
    platform: "https://www.descript.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $24/month",
    tags: ["video-editing", "audio", "transcription"],
    popularity: 80,
    lastUpdated: "2025-10-25",
  },
  {
    id: "18",
    name: "Mistral AI",
    category: "Generative AI",
    description: "European AI company with open-source and commercial language models.",
    platform: "https://mistral.ai",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + paid API",
    tags: ["language-model", "open-source", "european"],
    popularity: 79,
    lastUpdated: "2025-10-24",
  },
  {
    id: "19",
    name: "Cohere",
    category: "NLP Platform",
    description: "Enterprise NLP platform with language understanding and generation.",
    platform: "https://cohere.com",
    region: "Canada",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["nlp", "text-generation", "enterprise"],
    popularity: 78,
    lastUpdated: "2025-10-23",
  },
  {
    id: "20",
    name: "Together AI",
    category: "ML Infrastructure",
    description: "Compute platform for running and fine-tuning open-source models.",
    platform: "https://www.together.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["infrastructure", "models", "compute"],
    popularity: 77,
    lastUpdated: "2025-10-22",
  },
  {
    id: "21",
    name: "Grok",
    category: "Generative AI",
    description: "X AI's conversational model with real-time information access.",
    platform: "https://x.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "X Premium+ subscription",
    tags: ["language-model", "conversational", "real-time"],
    popularity: 82,
    lastUpdated: "2025-11-14",
  },
  {
    id: "22",
    name: "Granite",
    category: "Generative AI",
    description: "IBM's enterprise-focused large language model for business applications.",
    platform: "https://www.ibm.com/products/watsonx-ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "enterprise", "business"],
    popularity: 76,
    lastUpdated: "2025-11-14",
  },
  {
    id: "23",
    name: "Stable LM",
    category: "Generative AI",
    description: "Stability AI's open-source language model for text generation.",
    platform: "https://stability.ai",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "text-generation"],
    popularity: 75,
    lastUpdated: "2025-11-14",
  },
  {
    id: "24",
    name: "Command R+",
    category: "Generative AI",
    description: "Cohere's enhanced retrieval-augmented LLM with superior performance for RAG.",
    platform: "https://cohere.com/command",
    region: "Canada",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "rag", "enterprise", "retrieval"],
    popularity: 78,
    lastUpdated: "2025-11-14",
  },
  {
    id: "47",
    name: "Command R",
    category: "Generative AI",
    description: "Cohere's retrieval-augmented LLM optimized for enterprise RAG applications.",
    platform: "https://cohere.com/command",
    region: "Canada",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "rag", "enterprise", "retrieval"],
    popularity: 77,
    lastUpdated: "2025-11-14",
  },
  {
    id: "25",
    name: "Ernie Bot",
    category: "Generative AI",
    description: "Baidu's flagship generative AI model, one of China's first approved LLMs.",
    platform: "https://yiyan.baidu.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "chinese", "conversational"],
    popularity: 85,
    lastUpdated: "2025-11-14",
  },
  {
    id: "26",
    name: "Qwen",
    category: "Generative AI",
    description: "Alibaba's open-source large language model with multilingual capabilities.",
    platform: "https://qwenlm.github.io",
    region: "China",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "chinese", "multilingual"],
    popularity: 83,
    lastUpdated: "2025-11-14",
  },
  {
    id: "27",
    name: "Hunyuan",
    category: "Generative AI",
    description: "Tencent's generative AI model suite for text and multimodal tasks.",
    platform: "https://hunyuan.tencent.com",
    region: "China",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "multimodal", "chinese"],
    popularity: 81,
    lastUpdated: "2025-11-14",
  },
  {
    id: "28",
    name: "PanGu",
    category: "Generative AI",
    description: "Huawei's large-scale language model for enterprise and research applications.",
    platform: "https://www.huaweicloud.com/intl/en-us/product/pangu.html",
    region: "China",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "enterprise", "chinese"],
    popularity: 79,
    lastUpdated: "2025-11-14",
  },
  {
    id: "29",
    name: "Doubao",
    category: "Generative AI",
    description: "ByteDance's conversational AI model powering various applications.",
    platform: "https://www.doubao.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "conversational", "chinese"],
    popularity: 80,
    lastUpdated: "2025-11-14",
  },
  {
    id: "30",
    name: "DeepSeek-R1",
    category: "Generative AI",
    description: "Cutting-edge mixture-of-experts model with 685B parameters for advanced reasoning.",
    platform: "https://www.deepseek.com",
    region: "China",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "moe", "reasoning", "open-source"],
    popularity: 84,
    lastUpdated: "2025-11-14",
    isTrending: true,
  },
  {
    id: "31",
    name: "Zidong Taichu",
    category: "Generative AI",
    description: "Chinese Academy of Sciences' multimodal AI model for research.",
    platform: "https://www.ia.cas.cn",
    region: "China",
    accessType: "Free",
    pricing: "Research access",
    tags: ["language-model", "multimodal", "research", "chinese"],
    popularity: 72,
    lastUpdated: "2025-11-14",
  },
  {
    id: "32",
    name: "ChatGLM",
    category: "Generative AI",
    description: "Tsinghua University & Zhipu AI's bilingual conversational language model.",
    platform: "https://chatglm.cn",
    region: "China",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "bilingual", "open-source", "chinese"],
    popularity: 78,
    lastUpdated: "2025-11-14",
  },
  {
    id: "33",
    name: "Baichuan",
    category: "Generative AI",
    description: "Independent Chinese startup's widely benchmarked language model.",
    platform: "https://www.baichuan-ai.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid API",
    tags: ["language-model", "chinese", "startup"],
    popularity: 74,
    lastUpdated: "2025-11-14",
  },
  {
    id: "34",
    name: "Yi",
    category: "Generative AI",
    description: "01.AI's open-source LLM gaining international traction with strong performance.",
    platform: "https://www.01.ai",
    region: "China",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "chinese", "multilingual"],
    popularity: 76,
    lastUpdated: "2025-11-14",
  },
  {
    id: "48",
    name: "Phi-3",
    category: "Generative AI",
    description: "Microsoft Research's latest small language model with impressive performance.",
    platform: "https://azure.microsoft.com/en-us/products/phi-3",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "small-model", "efficient", "open-source"],
    popularity: 81,
    lastUpdated: "2025-11-14",
  },
  {
    id: "49",
    name: "Phi-2",
    category: "Generative AI",
    description: "Microsoft Research's 2.7B parameter efficient language model.",
    platform: "https://www.microsoft.com/en-us/research",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "small-model", "efficient", "open-source"],
    popularity: 78,
    lastUpdated: "2025-11-14",
  },
  {
    id: "50",
    name: "Phi-1",
    category: "Generative AI",
    description: "Microsoft Research's first small language model for code generation.",
    platform: "https://www.microsoft.com/en-us/research",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "small-model", "code-generation", "open-source"],
    popularity: 74,
    lastUpdated: "2025-11-14",
  },
  {
    id: "51",
    name: "Bloom",
    category: "Generative AI",
    description: "BigScience's 176B parameter multilingual open-source language model.",
    platform: "https://huggingface.co/bigscience/bloom",
    region: "EU",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "multilingual", "open-source", "research"],
    popularity: 79,
    lastUpdated: "2025-11-14",
  },
  {
    id: "52",
    name: "Falcon 180B",
    category: "Generative AI",
    description: "Technology Innovation Institute's 180B parameter open-source LLM.",
    platform: "https://falconllm.tii.ae",
    region: "UAE",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "large-scale"],
    popularity: 77,
    lastUpdated: "2025-11-14",
  },
  {
    id: "53",
    name: "Falcon 40B",
    category: "Generative AI",
    description: "Technology Innovation Institute's 40B parameter efficient open-source model.",
    platform: "https://falconllm.tii.ae",
    region: "UAE",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "efficient"],
    popularity: 75,
    lastUpdated: "2025-11-14",
  },
  {
    id: "54",
    name: "Jurassic-2",
    category: "Generative AI",
    description: "AI21 Labs' advanced language model with superior instruction following.",
    platform: "https://www.ai21.com",
    region: "Israel",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "enterprise"],
    popularity: 76,
    lastUpdated: "2025-11-14",
  },
  {
    id: "55",
    name: "Jurassic-1",
    category: "Generative AI",
    description: "AI21 Labs' first-generation 178B parameter language model.",
    platform: "https://www.ai21.com",
    region: "Israel",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "enterprise"],
    popularity: 72,
    lastUpdated: "2025-11-14",
  },
  {
    id: "56",
    name: "NLLB",
    category: "Generative AI",
    description: "Meta's No Language Left Behind model supporting 200+ languages.",
    platform: "https://ai.meta.com/research/no-language-left-behind/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "translation", "multilingual", "open-source"],
    popularity: 73,
    lastUpdated: "2025-11-14",
  },
  {
    id: "57",
    name: "Aleph Alpha Luminous",
    category: "Generative AI",
    description: "German enterprise-focused multimodal language model with European data sovereignty.",
    platform: "https://aleph-alpha.com",
    region: "EU",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "multimodal", "enterprise", "european"],
    popularity: 71,
    lastUpdated: "2025-11-14",
  },
  {
    id: "58",
    name: "Xiaomi LLM",
    category: "Generative AI",
    description: "Xiaomi's generative AI model for smartphone and IoT integration.",
    platform: "https://www.mi.com",
    region: "China",
    accessType: "Paid",
    pricing: "Device integration",
    tags: ["language-model", "chinese", "mobile", "iot"],
    popularity: 73,
    lastUpdated: "2025-11-14",
  },
  {
    id: "59",
    name: "Fourth Paradigm",
    category: "Generative AI",
    description: "Beijing AI firm's industry-specific large language model for enterprise.",
    platform: "https://www.4paradigm.com",
    region: "China",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "enterprise", "chinese", "industry"],
    popularity: 70,
    lastUpdated: "2025-11-14",
  },
  {
    id: "60",
    name: "iFlytek Spark",
    category: "Generative AI",
    description: "iFlytek's speech and education-focused language model.",
    platform: "https://www.iflytek.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "speech", "education", "chinese"],
    popularity: 75,
    lastUpdated: "2025-11-14",
  },
  {
    id: "61",
    name: "SenseTime SenseNova",
    category: "Generative AI",
    description: "SenseTime's multimodal model combining vision and text capabilities.",
    platform: "https://www.sensetime.com",
    region: "China",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "multimodal", "vision", "chinese"],
    popularity: 77,
    lastUpdated: "2025-11-14",
  },
  {
    id: "62",
    name: "JD Explore V1",
    category: "Generative AI",
    description: "JD.com's retail-oriented large language model for e-commerce.",
    platform: "https://www.jd.com",
    region: "China",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "retail", "e-commerce", "chinese"],
    popularity: 72,
    lastUpdated: "2025-11-14",
  },
  {
    id: "63",
    name: "Kunlun AI",
    category: "Generative AI",
    description: "Independent AI lab's large language model for research and applications.",
    platform: "https://www.kunlun.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "research", "chinese"],
    popularity: 69,
    lastUpdated: "2025-11-14",
  },
  {
    id: "64",
    name: "MiniMax",
    category: "Generative AI",
    description: "Chinese startup's conversational AI model with strong dialogue capabilities.",
    platform: "https://www.minimax.chat",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid API",
    tags: ["language-model", "conversational", "chinese", "startup"],
    popularity: 74,
    lastUpdated: "2025-11-14",
  },
  {
    id: "65",
    name: "Xiaoice",
    category: "Generative AI",
    description: "Emotional AI assistant model with empathetic conversation capabilities.",
    platform: "https://www.xiaoice.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "emotional-ai", "conversational", "chinese"],
    popularity: 76,
    lastUpdated: "2025-11-14",
  },
  {
    id: "66",
    name: "Wudao",
    category: "Generative AI",
    description: "Beijing Academy of AI's massive multimodal model with 1.75T parameters.",
    platform: "https://www.baai.ac.cn",
    region: "China",
    accessType: "Free",
    pricing: "Research access",
    tags: ["language-model", "multimodal", "research", "chinese", "large-scale"],
    popularity: 78,
    lastUpdated: "2025-11-14",
  },
  // MLOps and Infrastructure
  {
    id: "67",
    name: "AWS SageMaker",
    category: "ML Infrastructure",
    description: "Amazon's fully managed machine learning platform for building, training, and deploying models.",
    platform: "https://aws.amazon.com/sagemaker",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["mlops", "infrastructure", "aws", "training", "deployment"],
    popularity: 88,
    lastUpdated: "2025-01-15",
  },
  {
    id: "68",
    name: "Google Vertex AI",
    category: "ML Infrastructure",
    description: "Google Cloud's unified ML platform for building, deploying, and scaling AI models.",
    platform: "https://cloud.google.com/vertex-ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["mlops", "infrastructure", "gcp", "training", "deployment"],
    popularity: 86,
    lastUpdated: "2025-01-15",
  },
  {
    id: "69",
    name: "Azure Machine Learning",
    category: "ML Infrastructure",
    description: "Microsoft's cloud-based platform for building, training, and deploying ML models.",
    platform: "https://azure.microsoft.com/machine-learning",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["mlops", "infrastructure", "azure", "training", "deployment"],
    popularity: 85,
    lastUpdated: "2025-01-15",
  },
  {
    id: "70",
    name: "Databricks ML",
    category: "ML Infrastructure",
    description: "Unified analytics platform with ML capabilities including Dolly model integrations.",
    platform: "https://www.databricks.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["mlops", "infrastructure", "analytics", "spark", "dolly"],
    popularity: 84,
    lastUpdated: "2025-01-15",
  },
  {
    id: "71",
    name: "Weights & Biases",
    category: "ML Infrastructure",
    description: "MLOps platform for experiment tracking, model versioning, and collaboration.",
    platform: "https://wandb.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["mlops", "experiment-tracking", "monitoring", "collaboration"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  {
    id: "72",
    name: "Neptune.ai",
    category: "ML Infrastructure",
    description: "MLOps platform for experiment tracking, model registry, and monitoring.",
    platform: "https://neptune.ai",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["mlops", "experiment-tracking", "monitoring", "registry"],
    popularity: 75,
    lastUpdated: "2025-01-15",
  },
  {
    id: "73",
    name: "MLflow",
    category: "ML Infrastructure",
    description: "Open-source platform for managing the ML lifecycle including tracking, projects, and models.",
    platform: "https://mlflow.org",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["mlops", "experiment-tracking", "open-source", "lifecycle"],
    popularity: 80,
    lastUpdated: "2025-01-15",
  },
  {
    id: "74",
    name: "DVC",
    category: "ML Infrastructure",
    description: "Data Version Control - open-source tool for managing ML data and models with Git-like workflows.",
    platform: "https://dvc.org",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["mlops", "version-control", "data-management", "open-source"],
    popularity: 78,
    lastUpdated: "2025-01-15",
  },
  {
    id: "75",
    name: "Domino Data Lab",
    category: "ML Infrastructure",
    description: "Enterprise MLOps platform for data science teams to build and deploy models at scale.",
    platform: "https://www.dominodatalab.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["mlops", "enterprise", "data-science", "collaboration"],
    popularity: 72,
    lastUpdated: "2025-01-15",
  },
  {
    id: "76",
    name: "Tecton",
    category: "ML Infrastructure",
    description: "Feature store platform for managing, serving, and monitoring ML features at scale.",
    platform: "https://www.tecton.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["mlops", "feature-store", "enterprise", "features"],
    popularity: 74,
    lastUpdated: "2025-01-15",
  },
  {
    id: "77",
    name: "Pachyderm",
    category: "ML Infrastructure",
    description: "Data versioning and pipeline platform for reproducible ML workflows.",
    platform: "https://www.pachyderm.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["mlops", "data-versioning", "pipelines", "reproducibility"],
    popularity: 70,
    lastUpdated: "2025-01-15",
  },
  {
    id: "78",
    name: "Seldon Deploy",
    category: "ML Infrastructure",
    description: "Enterprise ML deployment platform for productionizing models with monitoring and explainability.",
    platform: "https://www.seldon.io",
    region: "UK",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["mlops", "deployment", "monitoring", "explainability"],
    popularity: 73,
    lastUpdated: "2025-01-15",
  },
  {
    id: "79",
    name: "Algorithmia",
    category: "ML Infrastructure",
    description: "MLOps platform for deploying, managing, and scaling ML models in production.",
    platform: "https://algorithmia.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["mlops", "deployment", "api", "scaling"],
    popularity: 71,
    lastUpdated: "2025-01-15",
  },
  // Vector Databases
  {
    id: "80",
    name: "Pinecone",
    category: "ML Infrastructure",
    description: "Managed vector database for building AI applications with semantic search and RAG.",
    platform: "https://www.pinecone.io",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["vector-db", "semantic-search", "rag", "embeddings"],
    popularity: 85,
    lastUpdated: "2025-01-15",
  },
  {
    id: "81",
    name: "Milvus",
    category: "ML Infrastructure",
    description: "Open-source vector database for scalable similarity search and AI applications.",
    platform: "https://milvus.io",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["vector-db", "semantic-search", "open-source", "scalable"],
    popularity: 83,
    lastUpdated: "2025-01-15",
  },
  {
    id: "82",
    name: "Weaviate",
    category: "ML Infrastructure",
    description: "Open-source vector database with built-in ML models for semantic search.",
    platform: "https://weaviate.io",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["vector-db", "semantic-search", "open-source", "graphql"],
    popularity: 81,
    lastUpdated: "2025-01-15",
  },
  {
    id: "83",
    name: "Vespa",
    category: "ML Infrastructure",
    description: "Open-source big data serving engine with vector search capabilities.",
    platform: "https://vespa.ai",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["vector-db", "search", "open-source", "big-data"],
    popularity: 76,
    lastUpdated: "2025-01-15",
  },
  {
    id: "84",
    name: "Redis Vector",
    category: "ML Infrastructure",
    description: "Redis with vector search capabilities for real-time similarity search.",
    platform: "https://redis.io",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["vector-db", "redis", "real-time", "search"],
    popularity: 79,
    lastUpdated: "2025-01-15",
  },
  {
    id: "85",
    name: "Qdrant",
    category: "ML Infrastructure",
    description: "Vector similarity search engine with extended filtering support.",
    platform: "https://qdrant.tech",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["vector-db", "similarity-search", "filtering", "rust"],
    popularity: 78,
    lastUpdated: "2025-01-15",
  },
  {
    id: "86",
    name: "Zilliz",
    category: "ML Infrastructure",
    description: "Cloud-native vector database built on Milvus for enterprise AI applications.",
    platform: "https://zilliz.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["vector-db", "cloud-native", "enterprise", "milvus"],
    popularity: 75,
    lastUpdated: "2025-01-15",
  },
  // Code Generation Tools
  {
    id: "87",
    name: "Replit Ghostwriter",
    category: "Code Generation",
    description: "AI-powered code completion and generation within the Replit development environment.",
    platform: "https://replit.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["code-generation", "ide", "completion", "developer-tools"],
    popularity: 77,
    lastUpdated: "2025-01-15",
  },
  {
    id: "88",
    name: "Tabnine",
    category: "Code Generation",
    description: "AI code completion tool that learns from your codebase to provide contextual suggestions.",
    platform: "https://www.tabnine.com",
    region: "Israel",
    accessType: "Freemium",
    pricing: "Free tier + $12-20/month",
    tags: ["code-generation", "completion", "ide", "developer-tools"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  {
    id: "89",
    name: "Amazon CodeWhisperer",
    category: "Code Generation",
    description: "AI-powered code generator that provides real-time code suggestions and security scans.",
    platform: "https://aws.amazon.com/codewhisperer",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["code-generation", "aws", "security", "completion"],
    popularity: 80,
    lastUpdated: "2025-01-15",
  },
  {
    id: "90",
    name: "Sourcegraph Cody",
    category: "Code Generation",
    description: "AI coding assistant that understands your entire codebase for better code generation.",
    platform: "https://sourcegraph.com/cody",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["code-generation", "assistant", "codebase", "developer-tools"],
    popularity: 79,
    lastUpdated: "2025-01-15",
  },
  {
    id: "91",
    name: "Codex",
    category: "Code Generation",
    description: "OpenAI's legacy code generation model, predecessor to GPT-4 for code tasks.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["code-generation", "legacy", "openai", "api"],
    popularity: 85,
    lastUpdated: "2025-01-15",
  },
  {
    id: "92",
    name: "Codeium",
    category: "Code Generation",
    description: "Free AI-powered code completion and chat assistant for developers.",
    platform: "https://codeium.com",
    region: "USA",
    accessType: "Free",
    pricing: "Free",
    tags: ["code-generation", "completion", "free", "developer-tools"],
    popularity: 81,
    lastUpdated: "2025-01-15",
  },

  // Content Writing Tools
  {
    id: "93",
    name: "Jasper",
    category: "Generative AI",
    description: "AI content creation platform for marketing copy, blogs, and creative writing.",
    platform: "https://www.jasper.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "$49-499/month",
    tags: ["content-writing", "marketing", "copywriting", "blogging"],
    popularity: 84,
    lastUpdated: "2025-01-15",
  },
  {
    id: "94",
    name: "Copy.ai",
    category: "Generative AI",
    description: "AI-powered copywriting tool for generating marketing content, ads, and social media posts.",
    platform: "https://www.copy.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $49/month",
    tags: ["content-writing", "marketing", "copywriting", "social-media"],
    popularity: 83,
    lastUpdated: "2025-01-15",
  },
  {
    id: "95",
    name: "Writesonic",
    category: "Generative AI",
    description: "AI writing assistant for creating blog posts, ads, product descriptions, and more.",
    platform: "https://writesonic.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $19-199/month",
    tags: ["content-writing", "blogging", "marketing", "seo"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  {
    id: "96",
    name: "Rytr",
    category: "Generative AI",
    description: "AI writing tool for creating content in 30+ languages with multiple tones and use cases.",
    platform: "https://rytr.me",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $9-29/month",
    tags: ["content-writing", "multilingual", "affordable", "blogging"],
    popularity: 80,
    lastUpdated: "2025-01-15",
  },
  {
    id: "97",
    name: "CopySmith",
    category: "Generative AI",
    description: "AI copywriting platform for e-commerce product descriptions and marketing content.",
    platform: "https://copysmith.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "$19-199/month",
    tags: ["content-writing", "e-commerce", "product-descriptions", "marketing"],
    popularity: 76,
    lastUpdated: "2025-01-15",
  },
  {
    id: "98",
    name: "Peppertype.ai",
    category: "Generative AI",
    description: "AI content writing tool for creating blog posts, social media content, and marketing copy.",
    platform: "https://www.peppertype.ai",
    region: "India",
    accessType: "Freemium",
    pricing: "Free tier + $25-199/month",
    tags: ["content-writing", "blogging", "social-media", "marketing"],
    popularity: 75,
    lastUpdated: "2025-01-15",
  },
  {
    id: "99",
    name: "ShortlyAI",
    category: "Generative AI",
    description: "AI writing assistant for long-form content, articles, and creative writing.",
    platform: "https://www.shortlyai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$65/month",
    tags: ["content-writing", "long-form", "articles", "creative"],
    popularity: 74,
    lastUpdated: "2025-01-15",
  },
  {
    id: "100",
    name: "SurferSEO",
    category: "Generative AI",
    description: "SEO content editor with AI-powered writing assistance and optimization.",
    platform: "https://surferseo.com",
    region: "EU",
    accessType: "Paid",
    pricing: "$89-239/month",
    tags: ["content-writing", "seo", "optimization", "marketing"],
    popularity: 79,
    lastUpdated: "2025-01-15",
  },
  {
    id: "101",
    name: "MarketMuse",
    category: "Generative AI",
    description: "AI-powered content strategy and optimization platform for SEO and content planning.",
    platform: "https://www.marketmuse.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["content-strategy", "seo", "optimization", "enterprise"],
    popularity: 77,
    lastUpdated: "2025-01-15",
  },
  // Search and QA Tools
  {
    id: "102",
    name: "Elicit",
    category: "Search/QA",
    description: "AI research assistant that helps find, summarize, and synthesize research papers.",
    platform: "https://elicit.org",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $10/month",
    tags: ["research", "academic", "papers", "synthesis"],
    popularity: 81,
    lastUpdated: "2025-01-15",
  },
  {
    id: "103",
    name: "Andi",
    category: "Search/QA",
    description: "AI-powered search engine that provides direct answers with source citations.",
    platform: "https://andisearch.com",
    region: "USA",
    accessType: "Free",
    pricing: "Free",
    tags: ["search", "qa", "answers", "citations"],
    popularity: 76,
    lastUpdated: "2025-01-15",
  },
  {
    id: "104",
    name: "You.com",
    category: "Search/QA",
    description: "AI search engine that combines web search with AI-powered answers and apps.",
    platform: "https://you.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["search", "qa", "ai-search", "apps"],
    popularity: 78,
    lastUpdated: "2025-01-15",
  },
  {
    id: "105",
    name: "Kagi",
    category: "Search/QA",
    description: "Privacy-focused search engine with AI features for better search results.",
    platform: "https://kagi.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$10/month",
    tags: ["search", "privacy", "ai-features", "premium"],
    popularity: 73,
    lastUpdated: "2025-01-15",
  },
  {
    id: "106",
    name: "Algolia Answers",
    category: "Search/QA",
    description: "AI-powered search API that understands natural language queries and intent.",
    platform: "https://www.algolia.com/products/answers",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["search", "api", "nlp", "enterprise"],
    popularity: 80,
    lastUpdated: "2025-01-15",
  },
  // Productivity and Note Taking
  {
    id: "107",
    name: "Notion AI",
    category: "Generative AI",
    description: "AI writing assistant integrated into Notion for content creation and summarization.",
    platform: "https://www.notion.so/product/ai",
    region: "USA",
    accessType: "Paid",
    pricing: "$10/month add-on",
    tags: ["productivity", "note-taking", "writing", "summarization"],
    popularity: 86,
    lastUpdated: "2025-01-15",
  },
  {
    id: "108",
    name: "Mem AI",
    category: "Generative AI",
    description: "AI-powered note-taking app that automatically organizes and connects your notes.",
    platform: "https://mem.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $10-15/month",
    tags: ["productivity", "note-taking", "organization", "knowledge-base"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  {
    id: "109",
    name: "Obsidian AI",
    category: "Generative AI",
    description: "AI plugins for Obsidian note-taking app including text generation and summarization.",
    platform: "https://obsidian.md",
    region: "USA",
    accessType: "Free",
    pricing: "Free (plugins)",
    tags: ["productivity", "note-taking", "plugins", "knowledge-graph"],
    popularity: 79,
    lastUpdated: "2025-01-15",
  },
  {
    id: "110",
    name: "Roam Research",
    category: "Generative AI",
    description: "Note-taking tool with AI integrations for knowledge management and research.",
    platform: "https://roamresearch.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$15/month",
    tags: ["productivity", "note-taking", "knowledge-graph", "research"],
    popularity: 77,
    lastUpdated: "2025-01-15",
  },
  {
    id: "111",
    name: "Coda AI",
    category: "Generative AI",
    description: "AI-powered document editor that combines docs, spreadsheets, and apps with AI assistance.",
    platform: "https://coda.io",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $12/month",
    tags: ["productivity", "documents", "collaboration", "automation"],
    popularity: 81,
    lastUpdated: "2025-01-15",
  },
  {
    id: "112",
    name: "Readwise Reader",
    category: "Generative AI",
    description: "Reading app with AI-powered highlights, summaries, and knowledge extraction.",
    platform: "https://readwise.io/read",
    region: "USA",
    accessType: "Paid",
    pricing: "$7.99/month",
    tags: ["productivity", "reading", "highlights", "summarization"],
    popularity: 78,
    lastUpdated: "2025-01-15",
  },
  // Design and Image Tools
  {
    id: "113",
    name: "Leonardo.ai",
    category: "Computer Vision",
    description: "AI image generation platform with fine-tuned models for game assets and creative content.",
    platform: "https://leonardo.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["image-generation", "game-assets", "creative", "fine-tuning"],
    popularity: 83,
    lastUpdated: "2025-01-15",
  },
  {
    id: "114",
    name: "Adobe Firefly",
    category: "Computer Vision",
    description: "Adobe's generative AI for creating images, vectors, and text effects.",
    platform: "https://www.adobe.com/products/firefly.html",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + Creative Cloud",
    tags: ["image-generation", "adobe", "creative", "commercial-safe"],
    popularity: 87,
    lastUpdated: "2025-01-15",
  },
  {
    id: "115",
    name: "Canva Magic Design",
    category: "Computer Vision",
    description: "AI-powered design tool within Canva for generating designs, images, and layouts.",
    platform: "https://www.canva.com",
    region: "Australia",
    accessType: "Freemium",
    pricing: "Free tier + $12.99/month",
    tags: ["design", "image-generation", "templates", "graphic-design"],
    popularity: 89,
    lastUpdated: "2025-01-15",
  },
  {
    id: "116",
    name: "DreamStudio",
    category: "Computer Vision",
    description: "Stability AI's official interface for Stable Diffusion image generation.",
    platform: "https://dreamstudio.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-per-image",
    tags: ["image-generation", "stable-diffusion", "stability-ai", "creative"],
    popularity: 80,
    lastUpdated: "2025-01-15",
  },
  {
    id: "117",
    name: "NightCafe",
    category: "Computer Vision",
    description: "AI art generator supporting multiple models including Stable Diffusion and DALL-E.",
    platform: "https://nightcafe.studio",
    region: "Australia",
    accessType: "Freemium",
    pricing: "Free tier + credits",
    tags: ["image-generation", "art", "multiple-models", "creative"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  // Video Generation Tools
  {
    id: "118",
    name: "Pika Labs",
    category: "Video Generation",
    description: "AI video generation platform for creating short videos from text and images.",
    platform: "https://pika.art",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["video-generation", "text-to-video", "creative", "short-videos"],
    popularity: 85,
    lastUpdated: "2025-01-15",
    isTrending: true,
  },
  {
    id: "119",
    name: "OpenAI Sora",
    category: "Video Generation",
    description: "OpenAI's text-to-video generation model creating realistic video scenes from prompts.",
    platform: "https://openai.com/sora",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["video-generation", "text-to-video", "openai", "realistic"],
    popularity: 92,
    lastUpdated: "2025-01-15",
    isTrending: true,
  },
  {
    id: "120",
    name: "Google Veo",
    category: "Video Generation",
    description: "Google's advanced video generation model for creating high-quality videos from text.",
    platform: "https://deepmind.google/technologies/veo",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["video-generation", "text-to-video", "google", "high-quality"],
    popularity: 88,
    lastUpdated: "2025-01-15",
  },
  {
    id: "121",
    name: "Meta Make-A-Video",
    category: "Video Generation",
    description: "Meta's research model for generating videos from text prompts and images.",
    platform: "https://makeavideo.studio.meta.com",
    region: "USA",
    accessType: "Free",
    pricing: "Research access",
    tags: ["video-generation", "text-to-video", "meta", "research"],
    popularity: 83,
    lastUpdated: "2025-01-15",
  },
  // Audio Tools
  {
    id: "122",
    name: "Resemble AI",
    category: "Audio/NLP",
    description: "AI voice cloning and text-to-speech platform for creating realistic voiceovers.",
    platform: "https://www.resemble.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["voice-cloning", "text-to-speech", "voiceover", "audio"],
    popularity: 79,
    lastUpdated: "2025-01-15",
  },
  {
    id: "123",
    name: "Murf.ai",
    category: "Audio/NLP",
    description: "AI voice generator with 120+ voices in 20+ languages for professional voiceovers.",
    platform: "https://murf.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $19-99/month",
    tags: ["text-to-speech", "voiceover", "multilingual", "audio"],
    popularity: 81,
    lastUpdated: "2025-01-15",
  },
  {
    id: "124",
    name: "Replica Studios",
    category: "Audio/NLP",
    description: "AI voice actors for games, films, and interactive media with emotional range.",
    platform: "https://replicastudios.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-per-use",
    tags: ["voice-acting", "games", "films", "emotional"],
    popularity: 77,
    lastUpdated: "2025-01-15",
  },
  {
    id: "125",
    name: "iZotope Neutron",
    category: "Audio/NLP",
    description: "AI-powered audio mixing and mastering tools for professional music production.",
    platform: "https://www.izotope.com/en/products/neutron.html",
    region: "USA",
    accessType: "Paid",
    pricing: "$249 one-time",
    tags: ["audio-mixing", "mastering", "music-production", "professional"],
    popularity: 75,
    lastUpdated: "2025-01-15",
  },
  // Chatbot and Conversational AI
  {
    id: "126",
    name: "Rasa",
    category: "NLP Platform",
    description: "Open-source conversational AI framework for building contextual chatbots and assistants.",
    platform: "https://rasa.com",
    region: "EU",
    accessType: "Freemium",
    pricing: "Open source + enterprise",
    tags: ["chatbot", "conversational-ai", "open-source", "nlp"],
    popularity: 84,
    lastUpdated: "2025-01-15",
  },
  {
    id: "127",
    name: "Dialogflow",
    category: "NLP Platform",
    description: "Google's conversational AI platform for building chatbots and voice assistants.",
    platform: "https://cloud.google.com/dialogflow",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["chatbot", "conversational-ai", "google", "voice-assistant"],
    popularity: 86,
    lastUpdated: "2025-01-15",
  },
  {
    id: "128",
    name: "Microsoft Bot Framework",
    category: "NLP Platform",
    description: "Microsoft's framework for building intelligent bots with Azure Bot Service integration.",
    platform: "https://dev.botframework.com",
    region: "USA",
    accessType: "Free",
    pricing: "Free SDK",
    tags: ["chatbot", "framework", "microsoft", "azure"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  {
    id: "129",
    name: "Kore.ai",
    category: "NLP Platform",
    description: "Enterprise conversational AI platform for building and deploying chatbots across channels.",
    platform: "https://kore.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["chatbot", "enterprise", "conversational-ai", "multi-channel"],
    popularity: 78,
    lastUpdated: "2025-01-15",
  },
  {
    id: "130",
    name: "Ada",
    category: "NLP Platform",
    description: "AI-powered customer service chatbot platform for automated support.",
    platform: "https://www.ada.cx",
    region: "Canada",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["chatbot", "customer-service", "support", "automation"],
    popularity: 80,
    lastUpdated: "2025-01-15",
  },
  {
    id: "131",
    name: "Intercom",
    category: "NLP Platform",
    description: "Customer messaging platform with AI features for automated support and engagement.",
    platform: "https://www.intercom.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$74-999/month",
    tags: ["chatbot", "customer-service", "messaging", "ai-features"],
    popularity: 85,
    lastUpdated: "2025-01-15",
  },
  {
    id: "132",
    name: "Drift",
    category: "NLP Platform",
    description: "Conversational marketing platform with AI chatbots for lead generation and sales.",
    platform: "https://www.drift.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["chatbot", "marketing", "sales", "lead-generation"],
    popularity: 79,
    lastUpdated: "2025-01-15",
  },
  {
    id: "133",
    name: "Landbot",
    category: "NLP Platform",
    description: "No-code chatbot builder for creating conversational experiences without coding.",
    platform: "https://landbot.io",
    region: "Spain",
    accessType: "Freemium",
    pricing: "Free tier + $30-100/month",
    tags: ["chatbot", "no-code", "conversational", "builder"],
    popularity: 76,
    lastUpdated: "2025-01-15",
  },
  // Business Automation
  {
    id: "134",
    name: "Zapier",
    category: "Generative AI",
    description: "Workflow automation platform with AI actions for connecting apps and automating tasks.",
    platform: "https://zapier.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $19.99-599/month",
    tags: ["automation", "workflows", "integrations", "ai-actions"],
    popularity: 88,
    lastUpdated: "2025-01-15",
  },
  {
    id: "135",
    name: "Make",
    category: "Generative AI",
    description: "Visual automation platform (formerly Integromat) with AI modules for workflow automation.",
    platform: "https://www.make.com",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + $9-299/month",
    tags: ["automation", "workflows", "visual", "ai-modules"],
    popularity: 83,
    lastUpdated: "2025-01-15",
  },
  {
    id: "136",
    name: "Microsoft Power Automate",
    category: "Generative AI",
    description: "Microsoft's workflow automation platform with AI features for business process automation.",
    platform: "https://powerautomate.microsoft.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$15-40/user/month",
    tags: ["automation", "workflows", "microsoft", "business"],
    popularity: 85,
    lastUpdated: "2025-01-15",
  },
  {
    id: "137",
    name: "Workato",
    category: "Generative AI",
    description: "Enterprise automation platform with AI apps for connecting systems and automating processes.",
    platform: "https://www.workato.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["automation", "enterprise", "integrations", "ai-apps"],
    popularity: 81,
    lastUpdated: "2025-01-15",
  },
  {
    id: "138",
    name: "Tray.io",
    category: "Generative AI",
    description: "Enterprise automation platform for building complex workflows and integrations.",
    platform: "https://tray.io",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["automation", "enterprise", "workflows", "integrations"],
    popularity: 78,
    lastUpdated: "2025-01-15",
  },
  // Analytics and BI
  {
    id: "139",
    name: "DataRobot",
    category: "ML Infrastructure",
    description: "Automated machine learning platform for building, deploying, and managing ML models.",
    platform: "https://www.datarobot.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["automl", "ml-platform", "analytics", "enterprise"],
    popularity: 84,
    lastUpdated: "2025-01-15",
  },
  {
    id: "140",
    name: "H2O.ai",
    category: "ML Infrastructure",
    description: "Open-source and commercial AutoML platform for machine learning and AI.",
    platform: "https://h2o.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Open source + enterprise",
    tags: ["automl", "ml-platform", "open-source", "analytics"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  {
    id: "141",
    name: "RapidMiner",
    category: "ML Infrastructure",
    description: "Data science platform with AutoML capabilities for predictive analytics and ML.",
    platform: "https://rapidminer.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["automl", "data-science", "analytics", "predictive"],
    popularity: 79,
    lastUpdated: "2025-01-15",
  },
  {
    id: "142",
    name: "Alteryx",
    category: "ML Infrastructure",
    description: "Analytics platform with AI capabilities for data preparation, blending, and advanced analytics.",
    platform: "https://www.alteryx.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["analytics", "data-preparation", "ai-features", "enterprise"],
    popularity: 83,
    lastUpdated: "2025-01-15",
  },
  {
    id: "143",
    name: "ThoughtSpot",
    category: "ML Infrastructure",
    description: "AI-powered analytics platform for natural language search and data exploration.",
    platform: "https://www.thoughtspot.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["analytics", "bi", "nlp-search", "data-exploration"],
    popularity: 81,
    lastUpdated: "2025-01-15",
  },
  // Enterprise Search and RAG
  {
    id: "144",
    name: "Haystack",
    category: "NLP Platform",
    description: "Deepset's open-source framework for building production-ready NLP and RAG applications.",
    platform: "https://haystack.deepset.ai",
    region: "EU",
    accessType: "Freemium",
    pricing: "Open source + enterprise",
    tags: ["rag", "nlp", "open-source", "enterprise-search"],
    popularity: 83,
    lastUpdated: "2025-01-15",
  },
  {
    id: "145",
    name: "LlamaIndex",
    category: "NLP Platform",
    description: "Data framework for connecting LLMs with external data sources for RAG applications.",
    platform: "https://www.llamaindex.ai",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["rag", "data-framework", "llm-integration", "open-source"],
    popularity: 85,
    lastUpdated: "2025-01-15",
  },
  {
    id: "146",
    name: "Semantic Kernel",
    category: "NLP Platform",
    description: "Microsoft's SDK for integrating AI models with applications using plugins and planners.",
    platform: "https://github.com/microsoft/semantic-kernel",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["rag", "sdk", "microsoft", "plugins"],
    popularity: 80,
    lastUpdated: "2025-01-15",
  },
  {
    id: "147",
    name: "AWS Kendra",
    category: "Search/QA",
    description: "Amazon's intelligent enterprise search service powered by machine learning.",
    platform: "https://aws.amazon.com/kendra",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["enterprise-search", "aws", "ml-powered", "intelligent"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  // Healthcare AI
  {
    id: "148",
    name: "DeepMind AlphaFold",
    category: "Generative AI",
    description: "AI system for predicting protein structures, revolutionizing biological research.",
    platform: "https://alphafold.ebi.ac.uk",
    region: "UK",
    accessType: "Free",
    pricing: "Free access",
    tags: ["biology", "protein-folding", "research", "healthcare"],
    popularity: 90,
    lastUpdated: "2025-01-15",
  },
  {
    id: "149",
    name: "Atomwise",
    category: "Generative AI",
    description: "AI-powered drug discovery platform for identifying potential therapeutic compounds.",
    platform: "https://www.atomwise.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["drug-discovery", "healthcare", "pharmaceutical", "molecular"],
    popularity: 78,
    lastUpdated: "2025-01-15",
  },
  {
    id: "150",
    name: "Insilico Medicine",
    category: "Generative AI",
    description: "AI-driven drug discovery company using generative models for pharmaceutical research.",
    platform: "https://insilico.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["drug-discovery", "healthcare", "generative", "pharmaceutical"],
    popularity: 76,
    lastUpdated: "2025-01-15",
  },
  {
    id: "151",
    name: "Tempus",
    category: "Generative AI",
    description: "AI-powered precision medicine platform for cancer treatment and clinical analytics.",
    platform: "https://www.tempus.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["healthcare", "precision-medicine", "cancer", "clinical-analytics"],
    popularity: 79,
    lastUpdated: "2025-01-15",
  },
  {
    id: "152",
    name: "PathAI",
    category: "Computer Vision",
    description: "AI-powered pathology platform for improving diagnostic accuracy in cancer detection.",
    platform: "https://www.pathai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["healthcare", "pathology", "cancer-detection", "diagnostics"],
    popularity: 77,
    lastUpdated: "2025-01-15",
  },
  {
    id: "153",
    name: "Abridge",
    category: "Audio/NLP",
    description: "AI-powered medical conversation recording and summarization for healthcare providers.",
    platform: "https://www.abridge.com",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["healthcare", "medical-notes", "summarization", "audio"],
    popularity: 75,
    lastUpdated: "2025-01-15",
  },
  // Legal AI
  {
    id: "154",
    name: "Casetext",
    category: "Generative AI",
    description: "AI legal research platform with Harvey AI for case law research and document analysis.",
    platform: "https://casetext.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$65-165/month",
    tags: ["legal", "research", "case-law", "document-analysis"],
    popularity: 81,
    lastUpdated: "2025-01-15",
  },
  {
    id: "155",
    name: "Harvey",
    category: "Generative AI",
    description: "AI legal assistant for law firms providing research, drafting, and analysis capabilities.",
    platform: "https://www.harvey.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["legal", "assistant", "research", "drafting"],
    popularity: 79,
    lastUpdated: "2025-01-15",
  },
  {
    id: "156",
    name: "Kira Systems",
    category: "Generative AI",
    description: "AI-powered contract analysis and document review platform for legal professionals.",
    platform: "https://kirasystems.com",
    region: "Canada",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["legal", "contract-analysis", "document-review", "enterprise"],
    popularity: 80,
    lastUpdated: "2025-01-15",
  },
  {
    id: "157",
    name: "Eigen Technologies",
    category: "Generative AI",
    description: "AI platform for document extraction and data extraction from legal and financial documents.",
    platform: "https://www.eigentech.com",
    region: "UK",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["legal", "document-extraction", "data-extraction", "enterprise"],
    popularity: 74,
    lastUpdated: "2025-01-15",
  },
  // Computer Vision Platforms
  {
    id: "158",
    name: "Clarifai",
    category: "Computer Vision",
    description: "AI platform for computer vision, natural language processing, and audio recognition.",
    platform: "https://www.clarifai.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["computer-vision", "nlp", "api", "platform"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  {
    id: "159",
    name: "Graphcore",
    category: "ML Infrastructure",
    description: "AI hardware and software solutions for accelerating machine learning workloads.",
    platform: "https://www.graphcore.ai",
    region: "UK",
    accessType: "Paid",
    pricing: "Hardware + software",
    tags: ["hardware", "ai-accelerator", "ml-infrastructure", "ipu"],
    popularity: 75,
    lastUpdated: "2025-01-15",
  },
  {
    id: "160",
    name: "SambaNova",
    category: "ML Infrastructure",
    description: "AI systems and models platform providing hardware and software solutions for enterprise AI.",
    platform: "https://sambanova.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["hardware", "ai-systems", "enterprise", "models"],
    popularity: 73,
    lastUpdated: "2025-01-15",
  },
  // Emerging Startups
  {
    id: "161",
    name: "Mythril AI",
    category: "Generative AI",
    description: "AI research and development company working on advanced language models.",
    platform: "https://mythril.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "research", "startup", "api"],
    popularity: 72,
    lastUpdated: "2025-01-15",
  },
  {
    id: "162",
    name: "Baidu Wenxin",
    category: "Generative AI",
    description: "Baidu's comprehensive AI platform with LLM, multimodal, and enterprise AI tools.",
    platform: "https://cloud.baidu.com/product/wenxinworkshop",
    region: "China",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "multimodal", "baidu", "enterprise"],
    popularity: 83,
    lastUpdated: "2025-01-15",
  },
  // Education and Learning
  {
    id: "163",
    name: "Duolingo Max",
    category: "Generative AI",
    description: "Duolingo's premium tier with LLM-powered features for personalized language learning.",
    platform: "https://www.duolingo.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$9.99/month",
    tags: ["education", "language-learning", "llm-powered", "personalized"],
    popularity: 84,
    lastUpdated: "2025-01-15",
  },
  {
    id: "164",
    name: "Khan Academy Khanmigo",
    category: "Generative AI",
    description: "AI tutor and teaching assistant integrated into Khan Academy for personalized learning.",
    platform: "https://www.khanacademy.org/khan-labs",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $9/month",
    tags: ["education", "tutoring", "personalized-learning", "khan-academy"],
    popularity: 82,
    lastUpdated: "2025-01-15",
  },
  {
    id: "165",
    name: "Quizlet Q-Chat",
    category: "Generative AI",
    description: "AI-powered study companion for Quizlet that helps students learn through conversation.",
    platform: "https://quizlet.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $7.99/month",
    tags: ["education", "study", "quizlet", "conversational"],
    popularity: 80,
    lastUpdated: "2025-01-15",
  },
  {
    id: "166",
    name: "Scribe",
    category: "Generative AI",
    description: "AI-powered tool for automatically creating step-by-step guides and documentation.",
    platform: "https://scribehow.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $12-29/month",
    tags: ["productivity", "documentation", "workflow", "guides"],
    popularity: 78,
    lastUpdated: "2025-01-15",
  },
]
