export interface AIEntry {
  id: string
  name: string
  category: string
  description: string
  platform: string
  region: string
  accessType: "Free" | "Freemium" | "Paid"
  pricing: string
  tags: string[]
  popularity: number
  lastUpdated: string
  isTrending?: boolean
}

export const aiEntries: AIEntry[] = [
  {
    id: "1",
    name: "GPT-4",
    category: "Generative AI",
    description: "Advanced language model for text generation, reasoning, and complex tasks.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$20/month",
    tags: ["language-model", "generative", "api"],
    popularity: 98,
    lastUpdated: "2025-11-10",
    isTrending: true,
  },
  {
    id: "35",
    name: "GPT-3.5",
    category: "Generative AI",
    description: "OpenAI's efficient language model, predecessor to GPT-4.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "api"],
    popularity: 92,
    lastUpdated: "2025-11-14",
  },
  {
    id: "36",
    name: "GPT-3",
    category: "Generative AI",
    description: "OpenAI's breakthrough 175B parameter language model.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "api"],
    popularity: 88,
    lastUpdated: "2025-11-14",
  },
  {
    id: "37",
    name: "GPT-2",
    category: "Generative AI",
    description: "OpenAI's 1.5B parameter model, open-sourced for research.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "generative", "open-source"],
    popularity: 75,
    lastUpdated: "2025-11-14",
  },
  {
    id: "38",
    name: "GPT-1",
    category: "Generative AI",
    description: "OpenAI's first generative pre-trained transformer model.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "generative", "research"],
    popularity: 65,
    lastUpdated: "2025-11-14",
  },
  {
    id: "2",
    name: "Claude 3",
    category: "Generative AI",
    description: "Anthropic's latest Claude family with Opus, Sonnet, and Haiku variants.",
    platform: "https://claude.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $20/month Pro",
    tags: ["language-model", "generative", "safe-ai", "constitutional-ai"],
    popularity: 95,
    lastUpdated: "2025-11-14",
    isTrending: true,
  },
  {
    id: "39",
    name: "Claude 2",
    category: "Generative AI",
    description: "Anthropic's second-generation constitutional AI model with improved capabilities.",
    platform: "https://claude.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "generative", "safe-ai"],
    popularity: 90,
    lastUpdated: "2025-11-14",
  },
  {
    id: "40",
    name: "Claude 1",
    category: "Generative AI",
    description: "Anthropic's first constitutional AI model focused on safety.",
    platform: "https://claude.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "safe-ai"],
    popularity: 82,
    lastUpdated: "2025-11-14",
  },
  {
    id: "3",
    name: "Midjourney",
    category: "Computer Vision",
    description: "AI image generation based on text prompts with exceptional artistic quality.",
    platform: "https://midjourney.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$10-120/month",
    tags: ["image-generation", "art", "design"],
    popularity: 92,
    lastUpdated: "2025-11-08",
    isTrending: true,
  },
  {
    id: "4",
    name: "DALL-E 3",
    category: "Computer Vision",
    description: "OpenAI image generation model creating realistic images from descriptions.",
    platform: "https://openai.com/dall-e-3",
    region: "USA",
    accessType: "Paid",
    pricing: "$0.02-0.04 per image",
    tags: ["image-generation", "vision", "api"],
    popularity: 90,
    lastUpdated: "2025-11-07",
  },
  {
    id: "5",
    name: "Whisper",
    category: "NLP/Audio",
    description: "Speech-to-text model supporting 99 languages with high accuracy.",
    platform: "https://openai.com/research/whisper",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["speech-to-text", "nlp", "audio"],
    popularity: 88,
    lastUpdated: "2025-11-06",
  },
  {
    id: "6",
    name: "YOLO v8",
    category: "Computer Vision",
    description: "State-of-the-art object detection model for real-time applications.",
    platform: "https://ultralytics.com",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["object-detection", "vision", "real-time"],
    popularity: 87,
    lastUpdated: "2025-11-05",
  },
  {
    id: "7",
    name: "Stable Diffusion",
    category: "Computer Vision",
    description: "Open-source image generation model with customizable parameters.",
    platform: "https://huggingface.co/stabilityai",
    region: "EU",
    accessType: "Free",
    pricing: "Open source",
    tags: ["image-generation", "open-source", "diffusion"],
    popularity: 89,
    lastUpdated: "2025-11-04",
  },
  {
    id: "8",
    name: "Hugging Face",
    category: "Multimodal Platform",
    description: "Hub for thousands of pre-trained AI models, datasets, and tools.",
    platform: "https://huggingface.co",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["platform", "models", "nlp", "vision"],
    popularity: 91,
    lastUpdated: "2025-11-03",
  },
  {
    id: "9",
    name: "LLaMA 3.1",
    category: "Generative AI",
    description: "Meta's latest open-source LLM with up to 405B parameters and extended capabilities.",
    platform: "https://ai.meta.com/llama/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "llm"],
    popularity: 89,
    lastUpdated: "2025-11-14",
    isTrending: true,
  },
  {
    id: "44",
    name: "LLaMA 3",
    category: "Generative AI",
    description: "Meta's third-generation open-source language model with improved performance.",
    platform: "https://ai.meta.com/llama/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "llm"],
    popularity: 88,
    lastUpdated: "2025-11-14",
  },
  {
    id: "45",
    name: "LLaMA 2",
    category: "Generative AI",
    description: "Meta's second-generation open-source LLM with commercial licensing.",
    platform: "https://ai.meta.com/llama/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "llm"],
    popularity: 86,
    lastUpdated: "2025-11-14",
  },
  {
    id: "46",
    name: "LLaMA 1",
    category: "Generative AI",
    description: "Meta's first-generation open-source large language model.",
    platform: "https://ai.meta.com/llama/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "research"],
    popularity: 80,
    lastUpdated: "2025-11-14",
  },
  {
    id: "10",
    name: "Gemini 1.5",
    category: "Generative AI",
    description: "Google's latest multimodal AI with extended context window and enhanced capabilities.",
    platform: "https://gemini.google.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $20/month Pro",
    tags: ["language-model", "multimodal", "generative", "long-context"],
    popularity: 94,
    lastUpdated: "2025-11-14",
    isTrending: true,
  },
  {
    id: "41",
    name: "Gemini 1",
    category: "Generative AI",
    description: "Google's first-generation multimodal AI model processing text, images, and code.",
    platform: "https://gemini.google.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "multimodal", "generative"],
    popularity: 91,
    lastUpdated: "2025-11-14",
  },
  {
    id: "42",
    name: "PaLM-2",
    category: "Generative AI",
    description: "Google's second-generation Pathways Language Model with improved reasoning.",
    platform: "https://ai.google/discover/palm2",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "reasoning"],
    popularity: 87,
    lastUpdated: "2025-11-14",
  },
  {
    id: "43",
    name: "PaLM",
    category: "Generative AI",
    description: "Google's Pathways Language Model with 540B parameters.",
    platform: "https://ai.google",
    region: "USA",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "research"],
    popularity: 83,
    lastUpdated: "2025-11-14",
  },
  {
    id: "11",
    name: "Runway",
    category: "Generative AI",
    description: "AI creative platform for video generation, editing, and visual effects.",
    platform: "https://runwayml.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $12-96/month",
    tags: ["video", "generative", "creative"],
    popularity: 85,
    lastUpdated: "2025-10-31",
    isTrending: true,
  },
  {
    id: "12",
    name: "ElevenLabs",
    category: "Audio/NLP",
    description: "Text-to-speech AI with natural sounding voices in 29+ languages.",
    platform: "https://elevenlabs.io",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + $11-99/month",
    tags: ["text-to-speech", "audio", "voice"],
    popularity: 84,
    lastUpdated: "2025-10-30",
  },
  {
    id: "13",
    name: "Copilot",
    category: "Code Generation",
    description: "AI code completion and generation assistant by GitHub.",
    platform: "https://github.com/features/copilot",
    region: "USA",
    accessType: "Paid",
    pricing: "$10/month individual",
    tags: ["code-generation", "programming", "developer-tools"],
    popularity: 93,
    lastUpdated: "2025-10-29",
  },
  {
    id: "14",
    name: "Synthesia",
    category: "Video Generation",
    description: "AI video generation platform with avatars and multi-language support.",
    platform: "https://www.synthesia.io",
    region: "EU",
    accessType: "Paid",
    pricing: "$30-480/month",
    tags: ["video", "avatar", "generative"],
    popularity: 82,
    lastUpdated: "2025-10-28",
  },
  {
    id: "15",
    name: "Perplexity AI",
    category: "Search/QA",
    description: "AI-powered search engine with real-time information and citations.",
    platform: "https://www.perplexity.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $20/month Pro",
    tags: ["search", "qa", "information-retrieval"],
    popularity: 83,
    lastUpdated: "2025-10-27",
  },
  {
    id: "16",
    name: "AutoGPT",
    category: "Autonomous AI",
    description: "Autonomous AI agent capable of completing complex tasks independently.",
    platform: "https://agentgpt.reworkd.ai",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["autonomous", "agent", "automation"],
    popularity: 81,
    lastUpdated: "2025-10-26",
  },
  {
    id: "17",
    name: "Descript",
    category: "Audio/Video Processing",
    description: "AI-powered video and podcast editing platform with transcription.",
    platform: "https://www.descript.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $24/month",
    tags: ["video-editing", "audio", "transcription"],
    popularity: 80,
    lastUpdated: "2025-10-25",
  },
  {
    id: "18",
    name: "Mistral AI",
    category: "Generative AI",
    description: "European AI company with open-source and commercial language models.",
    platform: "https://mistral.ai",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + paid API",
    tags: ["language-model", "open-source", "european"],
    popularity: 79,
    lastUpdated: "2025-10-24",
  },
  {
    id: "19",
    name: "Cohere",
    category: "NLP Platform",
    description: "Enterprise NLP platform with language understanding and generation.",
    platform: "https://cohere.com",
    region: "Canada",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["nlp", "text-generation", "enterprise"],
    popularity: 78,
    lastUpdated: "2025-10-23",
  },
  {
    id: "20",
    name: "Together AI",
    category: "ML Infrastructure",
    description: "Compute platform for running and fine-tuning open-source models.",
    platform: "https://www.together.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["infrastructure", "models", "compute"],
    popularity: 77,
    lastUpdated: "2025-10-22",
  },
  {
    id: "21",
    name: "Grok",
    category: "Generative AI",
    description: "X AI's conversational model with real-time information access.",
    platform: "https://x.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "X Premium+ subscription",
    tags: ["language-model", "conversational", "real-time"],
    popularity: 82,
    lastUpdated: "2025-11-14",
  },
  {
    id: "22",
    name: "Granite",
    category: "Generative AI",
    description: "IBM's enterprise-focused large language model for business applications.",
    platform: "https://www.ibm.com/products/watsonx-ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "enterprise", "business"],
    popularity: 76,
    lastUpdated: "2025-11-14",
  },
  {
    id: "23",
    name: "Stable LM",
    category: "Generative AI",
    description: "Stability AI's open-source language model for text generation.",
    platform: "https://stability.ai",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "text-generation"],
    popularity: 75,
    lastUpdated: "2025-11-14",
  },
  {
    id: "24",
    name: "Command R+",
    category: "Generative AI",
    description: "Cohere's enhanced retrieval-augmented LLM with superior performance for RAG.",
    platform: "https://cohere.com/command",
    region: "Canada",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "rag", "enterprise", "retrieval"],
    popularity: 78,
    lastUpdated: "2025-11-14",
  },
  {
    id: "47",
    name: "Command R",
    category: "Generative AI",
    description: "Cohere's retrieval-augmented LLM optimized for enterprise RAG applications.",
    platform: "https://cohere.com/command",
    region: "Canada",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "rag", "enterprise", "retrieval"],
    popularity: 77,
    lastUpdated: "2025-11-14",
  },
  {
    id: "25",
    name: "Ernie Bot",
    category: "Generative AI",
    description: "Baidu's flagship generative AI model, one of China's first approved LLMs.",
    platform: "https://yiyan.baidu.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "chinese", "conversational"],
    popularity: 85,
    lastUpdated: "2025-11-14",
  },
  {
    id: "26",
    name: "Qwen",
    category: "Generative AI",
    description: "Alibaba's open-source large language model with multilingual capabilities.",
    platform: "https://qwenlm.github.io",
    region: "China",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "chinese", "multilingual"],
    popularity: 83,
    lastUpdated: "2025-11-14",
  },
  {
    id: "27",
    name: "Hunyuan",
    category: "Generative AI",
    description: "Tencent's generative AI model suite for text and multimodal tasks.",
    platform: "https://hunyuan.tencent.com",
    region: "China",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "multimodal", "chinese"],
    popularity: 81,
    lastUpdated: "2025-11-14",
  },
  {
    id: "28",
    name: "PanGu",
    category: "Generative AI",
    description: "Huawei's large-scale language model for enterprise and research applications.",
    platform: "https://www.huaweicloud.com/intl/en-us/product/pangu.html",
    region: "China",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "enterprise", "chinese"],
    popularity: 79,
    lastUpdated: "2025-11-14",
  },
  {
    id: "29",
    name: "Doubao",
    category: "Generative AI",
    description: "ByteDance's conversational AI model powering various applications.",
    platform: "https://www.doubao.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "conversational", "chinese"],
    popularity: 80,
    lastUpdated: "2025-11-14",
  },
  {
    id: "30",
    name: "DeepSeek-R1",
    category: "Generative AI",
    description: "Cutting-edge mixture-of-experts model with 685B parameters for advanced reasoning.",
    platform: "https://www.deepseek.com",
    region: "China",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "moe", "reasoning", "open-source"],
    popularity: 84,
    lastUpdated: "2025-11-14",
    isTrending: true,
  },
  {
    id: "31",
    name: "Zidong Taichu",
    category: "Generative AI",
    description: "Chinese Academy of Sciences' multimodal AI model for research.",
    platform: "https://www.ia.cas.cn",
    region: "China",
    accessType: "Free",
    pricing: "Research access",
    tags: ["language-model", "multimodal", "research", "chinese"],
    popularity: 72,
    lastUpdated: "2025-11-14",
  },
  {
    id: "32",
    name: "ChatGLM",
    category: "Generative AI",
    description: "Tsinghua University & Zhipu AI's bilingual conversational language model.",
    platform: "https://chatglm.cn",
    region: "China",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "bilingual", "open-source", "chinese"],
    popularity: 78,
    lastUpdated: "2025-11-14",
  },
  {
    id: "33",
    name: "Baichuan",
    category: "Generative AI",
    description: "Independent Chinese startup's widely benchmarked language model.",
    platform: "https://www.baichuan-ai.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid API",
    tags: ["language-model", "chinese", "startup"],
    popularity: 74,
    lastUpdated: "2025-11-14",
  },
  {
    id: "34",
    name: "Yi",
    category: "Generative AI",
    description: "01.AI's open-source LLM gaining international traction with strong performance.",
    platform: "https://www.01.ai",
    region: "China",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "chinese", "multilingual"],
    popularity: 76,
    lastUpdated: "2025-11-14",
  },
  {
    id: "48",
    name: "Phi-3",
    category: "Generative AI",
    description: "Microsoft Research's latest small language model with impressive performance.",
    platform: "https://azure.microsoft.com/en-us/products/phi-3",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "small-model", "efficient", "open-source"],
    popularity: 81,
    lastUpdated: "2025-11-14",
  },
  {
    id: "49",
    name: "Phi-2",
    category: "Generative AI",
    description: "Microsoft Research's 2.7B parameter efficient language model.",
    platform: "https://www.microsoft.com/en-us/research",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "small-model", "efficient", "open-source"],
    popularity: 78,
    lastUpdated: "2025-11-14",
  },
  {
    id: "50",
    name: "Phi-1",
    category: "Generative AI",
    description: "Microsoft Research's first small language model for code generation.",
    platform: "https://www.microsoft.com/en-us/research",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "small-model", "code-generation", "open-source"],
    popularity: 74,
    lastUpdated: "2025-11-14",
  },
  {
    id: "51",
    name: "Bloom",
    category: "Generative AI",
    description: "BigScience's 176B parameter multilingual open-source language model.",
    platform: "https://huggingface.co/bigscience/bloom",
    region: "EU",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "multilingual", "open-source", "research"],
    popularity: 79,
    lastUpdated: "2025-11-14",
  },
  {
    id: "52",
    name: "Falcon 180B",
    category: "Generative AI",
    description: "Technology Innovation Institute's 180B parameter open-source LLM.",
    platform: "https://falconllm.tii.ae",
    region: "UAE",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "large-scale"],
    popularity: 77,
    lastUpdated: "2025-11-14",
  },
  {
    id: "53",
    name: "Falcon 40B",
    category: "Generative AI",
    description: "Technology Innovation Institute's 40B parameter efficient open-source model.",
    platform: "https://falconllm.tii.ae",
    region: "UAE",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "efficient"],
    popularity: 75,
    lastUpdated: "2025-11-14",
  },
  {
    id: "54",
    name: "Jurassic-2",
    category: "Generative AI",
    description: "AI21 Labs' advanced language model with superior instruction following.",
    platform: "https://www.ai21.com",
    region: "Israel",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "enterprise"],
    popularity: 76,
    lastUpdated: "2025-11-14",
  },
  {
    id: "55",
    name: "Jurassic-1",
    category: "Generative AI",
    description: "AI21 Labs' first-generation 178B parameter language model.",
    platform: "https://www.ai21.com",
    region: "Israel",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "generative", "enterprise"],
    popularity: 72,
    lastUpdated: "2025-11-14",
  },
  {
    id: "56",
    name: "NLLB",
    category: "Generative AI",
    description: "Meta's No Language Left Behind model supporting 200+ languages.",
    platform: "https://ai.meta.com/research/no-language-left-behind/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "translation", "multilingual", "open-source"],
    popularity: 73,
    lastUpdated: "2025-11-14",
  },
  {
    id: "57",
    name: "Aleph Alpha Luminous",
    category: "Generative AI",
    description: "German enterprise-focused multimodal language model with European data sovereignty.",
    platform: "https://aleph-alpha.com",
    region: "EU",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "multimodal", "enterprise", "european"],
    popularity: 71,
    lastUpdated: "2025-11-14",
  },
  {
    id: "58",
    name: "Xiaomi LLM",
    category: "Generative AI",
    description: "Xiaomi's generative AI model for smartphone and IoT integration.",
    platform: "https://www.mi.com",
    region: "China",
    accessType: "Paid",
    pricing: "Device integration",
    tags: ["language-model", "chinese", "mobile", "iot"],
    popularity: 73,
    lastUpdated: "2025-11-14",
  },
  {
    id: "59",
    name: "Fourth Paradigm",
    category: "Generative AI",
    description: "Beijing AI firm's industry-specific large language model for enterprise.",
    platform: "https://www.4paradigm.com",
    region: "China",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "enterprise", "chinese", "industry"],
    popularity: 70,
    lastUpdated: "2025-11-14",
  },
  {
    id: "60",
    name: "iFlytek Spark",
    category: "Generative AI",
    description: "iFlytek's speech and education-focused language model.",
    platform: "https://www.iflytek.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "speech", "education", "chinese"],
    popularity: 75,
    lastUpdated: "2025-11-14",
  },
  {
    id: "61",
    name: "SenseTime SenseNova",
    category: "Generative AI",
    description: "SenseTime's multimodal model combining vision and text capabilities.",
    platform: "https://www.sensetime.com",
    region: "China",
    accessType: "Paid",
    pricing: "API pricing",
    tags: ["language-model", "multimodal", "vision", "chinese"],
    popularity: 77,
    lastUpdated: "2025-11-14",
  },
  {
    id: "62",
    name: "JD Explore V1",
    category: "Generative AI",
    description: "JD.com's retail-oriented large language model for e-commerce.",
    platform: "https://www.jd.com",
    region: "China",
    accessType: "Paid",
    pricing: "Enterprise pricing",
    tags: ["language-model", "retail", "e-commerce", "chinese"],
    popularity: 72,
    lastUpdated: "2025-11-14",
  },
  {
    id: "63",
    name: "Kunlun AI",
    category: "Generative AI",
    description: "Independent AI lab's large language model for research and applications.",
    platform: "https://www.kunlun.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "research", "chinese"],
    popularity: 69,
    lastUpdated: "2025-11-14",
  },
  {
    id: "64",
    name: "MiniMax",
    category: "Generative AI",
    description: "Chinese startup's conversational AI model with strong dialogue capabilities.",
    platform: "https://www.minimax.chat",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid API",
    tags: ["language-model", "conversational", "chinese", "startup"],
    popularity: 74,
    lastUpdated: "2025-11-14",
  },
  {
    id: "65",
    name: "Xiaoice",
    category: "Generative AI",
    description: "Emotional AI assistant model with empathetic conversation capabilities.",
    platform: "https://www.xiaoice.com",
    region: "China",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["language-model", "emotional-ai", "conversational", "chinese"],
    popularity: 76,
    lastUpdated: "2025-11-14",
  },
  {
    id: "66",
    name: "Wudao",
    category: "Generative AI",
    description: "Beijing Academy of AI's massive multimodal model with 1.75T parameters.",
    platform: "https://www.baai.ac.cn",
    region: "China",
    accessType: "Free",
    pricing: "Research access",
    tags: ["language-model", "multimodal", "research", "chinese", "large-scale"],
    popularity: 78,
    lastUpdated: "2025-11-14",
  },
]
