export interface AIEntry {
  id: string
  name: string
  category: string
  description: string
  platform: string
  region: string
  accessType: "Free" | "Freemium" | "Paid"
  pricing: string
  tags: string[]
  popularity: number
  lastUpdated: string
  isTrending?: boolean
}

export const aiEntries: AIEntry[] = [
  {
    id: "1",
    name: "GPT-4",
    category: "Generative AI",
    description: "Advanced language model for text generation, reasoning, and complex tasks.",
    platform: "https://openai.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$20/month",
    tags: ["language-model", "generative", "api"],
    popularity: 98,
    lastUpdated: "2025-11-10",
    isTrending: true,
  },
  {
    id: "2",
    name: "Claude",
    category: "Generative AI",
    description: "Constitutional AI model by Anthropic focused on safety and reliability.",
    platform: "https://claude.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $20/month Pro",
    tags: ["language-model", "generative", "safe-ai"],
    popularity: 95,
    lastUpdated: "2025-11-09",
  },
  {
    id: "3",
    name: "Midjourney",
    category: "Computer Vision",
    description: "AI image generation based on text prompts with exceptional artistic quality.",
    platform: "https://midjourney.com",
    region: "USA",
    accessType: "Paid",
    pricing: "$10-120/month",
    tags: ["image-generation", "art", "design"],
    popularity: 92,
    lastUpdated: "2025-11-08",
    isTrending: true,
  },
  {
    id: "4",
    name: "DALL-E 3",
    category: "Computer Vision",
    description: "OpenAI image generation model creating realistic images from descriptions.",
    platform: "https://openai.com/dall-e-3",
    region: "USA",
    accessType: "Paid",
    pricing: "$0.02-0.04 per image",
    tags: ["image-generation", "vision", "api"],
    popularity: 90,
    lastUpdated: "2025-11-07",
  },
  {
    id: "5",
    name: "Whisper",
    category: "NLP/Audio",
    description: "Speech-to-text model supporting 99 languages with high accuracy.",
    platform: "https://openai.com/research/whisper",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["speech-to-text", "nlp", "audio"],
    popularity: 88,
    lastUpdated: "2025-11-06",
  },
  {
    id: "6",
    name: "YOLO v8",
    category: "Computer Vision",
    description: "State-of-the-art object detection model for real-time applications.",
    platform: "https://ultralytics.com",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["object-detection", "vision", "real-time"],
    popularity: 87,
    lastUpdated: "2025-11-05",
  },
  {
    id: "7",
    name: "Stable Diffusion",
    category: "Computer Vision",
    description: "Open-source image generation model with customizable parameters.",
    platform: "https://huggingface.co/stabilityai",
    region: "EU",
    accessType: "Free",
    pricing: "Open source",
    tags: ["image-generation", "open-source", "diffusion"],
    popularity: 89,
    lastUpdated: "2025-11-04",
  },
  {
    id: "8",
    name: "Hugging Face",
    category: "Multimodal Platform",
    description: "Hub for thousands of pre-trained AI models, datasets, and tools.",
    platform: "https://huggingface.co",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["platform", "models", "nlp", "vision"],
    popularity: 91,
    lastUpdated: "2025-11-03",
  },
  {
    id: "9",
    name: "Meta Llama 2",
    category: "Generative AI",
    description: "Open-source large language model by Meta with commercial licensing.",
    platform: "https://ai.meta.com/llama/",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["language-model", "open-source", "llm"],
    popularity: 86,
    lastUpdated: "2025-11-02",
  },
  {
    id: "10",
    name: "Gemini",
    category: "Generative AI",
    description: "Google multimodal AI model processing text, images, and code.",
    platform: "https://gemini.google.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $20/month Pro",
    tags: ["language-model", "multimodal", "generative"],
    popularity: 94,
    lastUpdated: "2025-11-01",
    isTrending: true,
  },
  {
    id: "11",
    name: "Runway",
    category: "Generative AI",
    description: "AI creative platform for video generation, editing, and visual effects.",
    platform: "https://runwayml.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $12-96/month",
    tags: ["video", "generative", "creative"],
    popularity: 85,
    lastUpdated: "2025-10-31",
    isTrending: true,
  },
  {
    id: "12",
    name: "ElevenLabs",
    category: "Audio/NLP",
    description: "Text-to-speech AI with natural sounding voices in 29+ languages.",
    platform: "https://elevenlabs.io",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + $11-99/month",
    tags: ["text-to-speech", "audio", "voice"],
    popularity: 84,
    lastUpdated: "2025-10-30",
  },
  {
    id: "13",
    name: "Copilot",
    category: "Code Generation",
    description: "AI code completion and generation assistant by GitHub.",
    platform: "https://github.com/features/copilot",
    region: "USA",
    accessType: "Paid",
    pricing: "$10/month individual",
    tags: ["code-generation", "programming", "developer-tools"],
    popularity: 93,
    lastUpdated: "2025-10-29",
  },
  {
    id: "14",
    name: "Synthesia",
    category: "Video Generation",
    description: "AI video generation platform with avatars and multi-language support.",
    platform: "https://www.synthesia.io",
    region: "EU",
    accessType: "Paid",
    pricing: "$30-480/month",
    tags: ["video", "avatar", "generative"],
    popularity: 82,
    lastUpdated: "2025-10-28",
  },
  {
    id: "15",
    name: "Perplexity AI",
    category: "Search/QA",
    description: "AI-powered search engine with real-time information and citations.",
    platform: "https://www.perplexity.ai",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $20/month Pro",
    tags: ["search", "qa", "information-retrieval"],
    popularity: 83,
    lastUpdated: "2025-10-27",
  },
  {
    id: "16",
    name: "AutoGPT",
    category: "Autonomous AI",
    description: "Autonomous AI agent capable of completing complex tasks independently.",
    platform: "https://agentgpt.reworkd.ai",
    region: "USA",
    accessType: "Free",
    pricing: "Open source",
    tags: ["autonomous", "agent", "automation"],
    popularity: 81,
    lastUpdated: "2025-10-26",
  },
  {
    id: "17",
    name: "Descript",
    category: "Audio/Video Processing",
    description: "AI-powered video and podcast editing platform with transcription.",
    platform: "https://www.descript.com",
    region: "USA",
    accessType: "Freemium",
    pricing: "Free tier + $24/month",
    tags: ["video-editing", "audio", "transcription"],
    popularity: 80,
    lastUpdated: "2025-10-25",
  },
  {
    id: "18",
    name: "Mistral AI",
    category: "Generative AI",
    description: "European AI company with open-source and commercial language models.",
    platform: "https://mistral.ai",
    region: "EU",
    accessType: "Freemium",
    pricing: "Free tier + paid API",
    tags: ["language-model", "open-source", "european"],
    popularity: 79,
    lastUpdated: "2025-10-24",
  },
  {
    id: "19",
    name: "Cohere",
    category: "NLP Platform",
    description: "Enterprise NLP platform with language understanding and generation.",
    platform: "https://cohere.com",
    region: "Canada",
    accessType: "Freemium",
    pricing: "Free tier + paid",
    tags: ["nlp", "text-generation", "enterprise"],
    popularity: 78,
    lastUpdated: "2025-10-23",
  },
  {
    id: "20",
    name: "Together AI",
    category: "ML Infrastructure",
    description: "Compute platform for running and fine-tuning open-source models.",
    platform: "https://www.together.ai",
    region: "USA",
    accessType: "Paid",
    pricing: "Pay-as-you-go",
    tags: ["infrastructure", "models", "compute"],
    popularity: 77,
    lastUpdated: "2025-10-22",
  },
]
