/**
 * Embedding Service - Generates semantic embeddings for AI tool search
 *
 * Creates 768-dimensional vectors capturing the semantic meaning of text.
 *
 * ===========================================================================
 * THIS FILE INTENTIONALLY STILL USES GEMINI. Do not "finish" the migration.
 * ===========================================================================
 * Every generative/reasoning path in this app moved to Claude (lib/claude.ts,
 * lib/claude-nlp.ts, lib/search-pipeline.ts, lib/recommend.ts). Embeddings did
 * not, for two reasons:
 *
 *  1. Anthropic has no embeddings API. There is no Claude embedding model to
 *     migrate to.
 *  2. More importantly, the ~257k vectors already stored in ai_tools.embedding
 *     were generated by gemini-embedding-001. Embeddings from different models
 *     occupy different vector spaces and are NOT comparable — a query embedded
 *     with any other model would return meaningless cosine distances against
 *     the stored corpus. Switching provider here therefore requires
 *     re-embedding all 257k rows first, which is a deliberate, costed
 *     migration and not a drop-in swap.
 *
 * If GEMINI_API_KEY is unset, generateEmbedding returns null and the search
 * path degrades to FTS-only retrieval (search_tools_advanced accepts a null
 * query_embedding by design). Cached embeddings in the search_cache table keep
 * working regardless, since they were already computed.
 */

import { GoogleGenerativeAI } from "@google/generative-ai"
import { getSupabaseAdmin } from "./supabase"
import { logger } from "./logger"

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "")

// Gemini's embedding model (gemini-embedding-001 replaced text-embedding-004 which was shut down Jan 2026)
const EMBEDDING_MODEL = "gemini-embedding-001"

// Cache embeddings in memory to reduce API calls
const embeddingCache = new Map<string, number[]>()
const CACHE_MAX_SIZE = 1000

// Hard per-call timeout. Without this, a hanging (not erroring) call to Gemini's embedding
// endpoint has no way to be cut off — this was the cause of full 30s Vercel timeouts with
// zero Postgres involvement, since the request never even reached search_tools_advanced.
const EMBEDDING_TIMEOUT_MS = 6000

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T> {
    return new Promise<T>((resolve, reject) => {
        const timer = setTimeout(() => {
            reject(Object.assign(new Error(`Embedding generation timed out after ${ms}ms`), { status: 503, isTimeout: true }))
        }, ms)
        promise.then(
            (val) => { clearTimeout(timer); resolve(val) },
            (err) => { clearTimeout(timer); reject(err) }
        )
    })
}

/**
 * Generate an embedding vector for the given text.
 *
 * NOTE: no retry-with-backoff here on purpose. This is called from a user-facing request
 * path with a hard deadline (Vercel maxDuration). A single bounded attempt that fails fast
 * to null lets hybridSearch() fall back to FTS-only search immediately, rather than a
 * multi-second retry chain risking a full request timeout for the same coin-flip outcome.
 */
export async function generateEmbedding(text: string): Promise<number[] | null> {
    if (!process.env.GEMINI_API_KEY) {
        logger.warn("[Embeddings] GEMINI_API_KEY is not set")
        return null
    }

    if (!text || text.trim().length === 0) {
        return null
    }

    // Check cache first
    const cacheKey = text.toLowerCase().trim().substring(0, 200)
    if (embeddingCache.has(cacheKey)) {
        return embeddingCache.get(cacheKey)!
    }

    try {
        const model = genAI.getGenerativeModel({ model: EMBEDDING_MODEL })
        const result = await withTimeout(
            model.embedContent({
                content: { role: 'user', parts: [{ text }] },
                outputDimensionality: 768
            } as any),
            EMBEDDING_TIMEOUT_MS
        )
        const embedding = result.embedding.values

        // Cache the result
        if (embeddingCache.size >= CACHE_MAX_SIZE) {
            const firstKey = embeddingCache.keys().next().value
            if (firstKey) embeddingCache.delete(firstKey)
        }
        embeddingCache.set(cacheKey, embedding)

        return embedding
    } catch (error: any) {
        console.error(`[Embeddings] Error generating embedding:`, error?.message || error)
        return null // No retry — caller (hybridSearch) already falls back to FTS-only on null
    }
}

/**
 * Generate embedding for search query with retry logic
 */
export async function generateQueryEmbedding(query: string): Promise<number[] | null> {
    // Clean and prepare the query
    const cleanQuery = query
        .toLowerCase()
        .replace(/[^\w\s-]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()

    if (cleanQuery.length < 3) {
        return null
    }

    // Add context to improve search quality
    const enhancedQuery = `AI tool for: ${cleanQuery}`

    return await generateEmbedding(enhancedQuery)
}

/**
 * Generate embedding for a tool (name + description combined)
 */
export async function generateToolEmbedding(
    name: string,
    description: string,
    category?: string,
    tags?: string[]
): Promise<number[] | null> {
    // Combine tool information for rich embedding
    const parts = [
        name,
        description || "",
        category ? `Category: ${category}` : "",
        tags && tags.length > 0 ? `Tags: ${tags.join(", ")}` : ""
    ].filter(Boolean)

    const text = parts.join(". ").substring(0, 2000) // Limit text length

    return await generateEmbedding(text)
}

/**
 * Batch generate embeddings for multiple tools
 * Includes rate limiting to avoid quota issues
 */
export async function batchGenerateEmbeddings(
    tools: Array<{
        id: string
        name: string
        description?: string | null
        category?: string
        tags?: string[] | null
    }>,
    onProgress?: (completed: number, total: number) => void
): Promise<Map<string, number[]>> {
    const results = new Map<string, number[]>()
    const batchSize = 3 // Process 3 at a time (conservative to avoid rate limits)
    const delayMs = 500 // Delay between batches to avoid rate limits
    let nullCount = 0

    for (let i = 0; i < tools.length; i += batchSize) {
        const batch = tools.slice(i, i + batchSize)

        await Promise.all(
            batch.map(async (tool) => {
                const embedding = await generateToolEmbedding(
                    tool.name,
                    tool.description || "",
                    tool.category,
                    tool.tags || []
                )
                if (embedding) {
                    results.set(tool.id, embedding)
                } else {
                    nullCount++
                }
            })
        )

        if (onProgress) {
            onProgress(Math.min(i + batchSize, tools.length), tools.length)
        }

        // If we're getting too many nulls, slow down significantly
        if (nullCount > 5) {
            console.warn(`[Embeddings] Many failures (${nullCount}), slowing down...`)
            await new Promise(resolve => setTimeout(resolve, 3000))
            nullCount = 0 // Reset counter
        }

        // Rate limit delay
        if (i + batchSize < tools.length) {
            await new Promise(resolve => setTimeout(resolve, delayMs))
        }
    }

    console.log(`[Embeddings] Batch complete: ${results.size} succeeded, ${nullCount} failed out of ${tools.length}`)
    return results
}

/**
 * Perform semantic search using embeddings
 */
export async function semanticSearch(
    query: string,
    limit: number = 20,
    threshold: number = 0.5
): Promise<Array<{
    id: string
    name: string
    category: string
    description: string
    platform: string
    region?: string
    access_type?: string
    pricing?: string
    tags?: string[]
    popularity?: number
    last_updated?: string
    is_trending?: boolean
    image?: string
    similarity: number
}>> {
    const queryEmbedding = await generateQueryEmbedding(query)

    if (!queryEmbedding) {
        logger.warn("[Embeddings] Could not generate query embedding")
        return []
    }

    const supabase = getSupabaseAdmin()

    try {
        // Use the semantic search function we created
        const { data, error } = await supabase.rpc('search_tools_semantic', {
            query_embedding: queryEmbedding,
            match_threshold: threshold,
            match_count: limit
        })

        if (error) {
            logger.error("[Embeddings] Semantic search error:", error)
            return []
        }

        return data || []
    } catch (error) {
        logger.error("[Embeddings] Semantic search failed:", error)
        return []
    }
}

/**
 * Hybrid search - combines semantic + keyword search
 * Returns results in a normalized shape ready for the ranking pipeline.
 */
export interface HybridSearchResult {
    // Identity
    id: string
    title: string
    description: string
    url: string
    category: string
    platform: string
    pricing: string
    tags: string[]
    // Normalized scores (0–1, 3 decimal places)
    keyword_score: number
    vector_score: number
    popularity_score: number
    source_trust_score: number
    combined_score: number
    // Metadata
    freshness_date: string | null
    is_trending: boolean
    // Raw DB fields preserved for downstream consumers
    region?: string
    access_type?: string
    popularity?: number
    last_updated?: string
    image?: string
    similarity: number
    fts_score?: number
}

/**
 * Tagged result so the caller (route.ts) can tell "the database/RPC is broken"
 * apart from "nothing matched" — both used to collapse to the same empty
 * array, which made it impossible to decide differently for each case (a DB
 * error should fall back to FTS-only/traditional search without touching the
 * self-healing discovery flow; a genuine zero-match result is exactly what
 * self-healing discovery exists for).
 */
export type HybridSearchResponse =
    | {
        status: 'ok'
        results: HybridSearchResult[]
        cachedEmbeddingAt?: string | null
        /**
         * Whether a query embedding was actually available — i.e. whether the
         * SEMANTIC tier contributed at all.
         *
         * Distinct from `status`. This function returns 'ok' whenever the RPC
         * succeeds, and the RPC runs perfectly well with a null embedding by
         * leaning on its full-text tiers. So 'ok' means the path ran, not that
         * meaning was involved. Conflating the two made an eval report
         * "retrieval mix hybrid:26" for runs where semantic may have been
         * absent — a measurement that quietly described the wrong thing.
         *
         * `cachedEmbeddingAt` cannot answer this: it is null both when no
         * embedding existed AND when a fresh one was just generated.
         */
        usedEmbedding: boolean
    }
    | { status: 'error'; results: []; errorReason: string }

export async function hybridSearch(
    query: string,
    limit: number = 30,
    threshold: number = 0.20,
    extraKeywords: string[] = []
): Promise<HybridSearchResponse> {
    const supabase = getSupabaseAdmin()

    // 1. Try to fetch embedding from permanent cache to save tokens
    let queryEmbedding: number[] | null = null;
    let cachedEmbeddingAt: string | null = null;
    const cleanQuery = query.toLowerCase().trim();

    // Has this query been seen before? Distinct from "does it have an
    // embedding" — the difference is what makes the lazy path below possible.
    let querySeenBefore = false;

    try {
        const { data: cached } = await supabase
            .from('search_cache')
            .select('semantic_embedding, created_at')
            .eq('query_text', cleanQuery)
            // maybeSingle, not single: an absent row is the normal first-sighting
            // case and must be distinguishable from a row that exists without an
            // embedding, not collapsed into the same catch block.
            .maybeSingle()

        if (cached) {
            querySeenBefore = true;
            if (cached.semantic_embedding) {
                queryEmbedding = cached.semantic_embedding;
                cachedEmbeddingAt = cached.created_at || null;
                logger.info("[Embeddings] Using heavily cached query embedding for tokens!")
                // Update last_used asynchronously
                supabase.from('search_cache').update({
                    last_used_at: new Date().toISOString(),
                }).eq('query_text', cleanQuery).then();
            }
        }
    } catch (e) {
        // Table doesn't exist yet, or an unexpected read failure. Treating this
        // as a first sighting is the safe default: it costs FTS-only results
        // rather than an embedding call.
    }

    // 2. Embed on the SECOND sighting, not the first.
    //
    // Search runs as you type, so the server sees every intermediate string.
    // Measured on the real search_cache (excluding this project's own test
    // traffic): 321 of 444 rows are strict prefixes of another row — keystroke
    // fragments like the chain "ai t", "ai tt", "ai too", "ai tool", "ai toold"
    // — and 251 of those had spent an embedding call. 338 of 444 queries were
    // never searched a second time. So roughly 70% of the embedding budget was
    // going to strings nobody meant to submit, and semantic similarity for "ai
    // t" is meaningless regardless.
    //
    // That budget is the binding constraint on the whole product: it is shared
    // with the tool-embedding backfill (coverage was 11%) and with goal
    // decomposition, which is the one unfinished piece of Phase 3.
    //
    // A LENGTH OR WORD-COUNT GATE WAS TRIED FIRST AND REJECTED on measurement:
    // no threshold separates fragments from real queries. At ">= 3 words and
    // >= 12 chars" it blocks 58% of fragments but also 61% of real queries,
    // throwing away "magic slides" and "grok xai". Recurrence discriminates;
    // length does not.
    //
    // THE TRADE, stated plainly: the first search of a genuinely new query gets
    // FTS-only retrieval rather than hybrid, and the retrieval tier does change
    // which tools come back. The second identical search gets full semantic
    // search. This was a deliberate product decision, not an optimisation.
    if (!queryEmbedding) {
        if (querySeenBefore) {
            queryEmbedding = await generateQueryEmbedding(query)
            if (queryEmbedding) {
                try {
                    supabase.from('search_cache').update({
                        semantic_embedding: queryEmbedding,
                        last_used_at: new Date().toISOString(),
                    }).eq('query_text', cleanQuery).then()
                } catch (err) { }
            } else {
                logger.info("[Embeddings] No embedding available, using FTS-only advanced search fallback")
            }
        } else {
            // Record the sighting so a repeat of this query earns an embedding.
            // No embedding is generated or stored on this path.
            try {
                supabase.from('search_cache').upsert({
                    query_text: cleanQuery,
                    last_used_at: new Date().toISOString(),
                }, { onConflict: 'query_text' }).then()
            } catch (err) { }
            logger.info(`[Embeddings] First sighting of "${cleanQuery}" — FTS-only this time, embedding on repeat`)
        }
    }

    try {
        const { data, error } = await supabase.rpc('search_tools_advanced', {
            search_query: query,
            query_embedding: queryEmbedding,
            match_threshold: threshold,
            match_count: limit,
            extra_keywords: extraKeywords.length > 0 ? extraKeywords : null
        })

        if (error) {
            if (error.message?.includes('does not exist')) {
                logger.warn("[Embeddings] Advanced hybrid search function not found. Did you run the migration?")
                return { status: 'error', results: [], errorReason: 'rpc_missing' }
            }
            logger.error("[Embeddings] Hybrid search error:", error)
            return { status: 'error', results: [], errorReason: error.message || 'rpc_error' }
        }

        if (!data || data.length === 0) {
            return { status: 'ok', results: [], cachedEmbeddingAt, usedEmbedding: Boolean(queryEmbedding) }
        }

        // Transform raw Supabase rows into the normalized ranking-ready shape
        const results = data.map((item: any): HybridSearchResult => ({
            // Identity
            id: item.id,
            title: item.name,
            description: item.description || '',
            url: item.id,
            category: item.category,
            platform: item.platform,
            pricing: item.pricing || '',
            tags: item.tags || [],
            // Normalized scores — parseFloat + toFixed(3) to eliminate FP noise
            keyword_score: parseFloat((item.keyword_score || 0).toFixed(3)),
            vector_score: parseFloat((item.similarity || 0).toFixed(3)),
            popularity_score: parseFloat(Math.min((item.popularity || 0) / 10000, 1).toFixed(3)),
            source_trust_score: parseFloat((item.source_trust_score || 0).toFixed(3)),
            combined_score: parseFloat((item.combined_score || 0).toFixed(3)),
            // Metadata
            freshness_date: item.last_updated || null,
            is_trending: item.is_trending || false,
            // Raw DB fields preserved
            region: item.region || 'Global',
            access_type: item.access_type || 'Freemium',
            popularity: item.popularity || 0,
            last_updated: item.last_updated || '',
            image: item.image || '',
            similarity: parseFloat((item.similarity || 0).toFixed(3)),
            fts_score: parseFloat((item.fts_score || 0).toFixed(3)),
        }))

        return { status: 'ok', results, cachedEmbeddingAt, usedEmbedding: Boolean(queryEmbedding) }
    } catch (error: any) {
        logger.error("[Embeddings] Hybrid search failed:", error)
        return { status: 'error', results: [], errorReason: error?.message || 'exception' }
    }
}

/**
 * Look up an existing tool whose name is a close fuzzy match to `name`.
 * Used before inserting a self-healing-discovery tool so Gemini can't create
 * a duplicate of an existing tool under a slightly different name (e.g.
 * "ChatGPT" vs "Chat GPT"). Returns null on no match OR on any DB error —
 * callers should treat both the same way (proceed with insertion) since this
 * is a best-effort guard, not a correctness requirement.
 */
export async function findSimilarToolByName(
    name: string,
    threshold: number = 0.35
): Promise<{ id: string; name: string; similarity_score: number } | null> {
    if (!name || !name.trim()) return null

    const supabase = getSupabaseAdmin()

    try {
        const { data, error } = await supabase.rpc('find_similar_tool_name', {
            p_name: name,
            p_threshold: threshold,
        })

        if (error) {
            if (error.message?.includes('does not exist')) {
                logger.warn("[Embeddings] find_similar_tool_name function not found. Did you run the migration?")
            } else {
                logger.warn("[Embeddings] find_similar_tool_name error:", error)
            }
            return null
        }

        return data && data.length > 0 ? data[0] : null
    } catch (error) {
        logger.warn("[Embeddings] find_similar_tool_name failed:", error)
        return null
    }
}

/**
 * Update a single tool's embedding in the database
 */
export async function updateToolEmbedding(toolId: string): Promise<boolean> {
    const supabase = getSupabaseAdmin()

    // Fetch the tool
    const { data: tool, error: fetchError } = await supabase
        .from('ai_tools')
        .select('id, name, description, category, tags')
        .eq('id', toolId)
        .single()

    if (fetchError || !tool) {
        logger.error("[Embeddings] Tool not found:", toolId)
        return false
    }

    // Generate embedding
    const embedding = await generateToolEmbedding(
        tool.name,
        tool.description,
        tool.category,
        tool.tags
    )

    if (!embedding) {
        logger.error("[Embeddings] Could not generate embedding for:", toolId)
        return false
    }

    // Update the tool with the embedding
    const { error: updateError } = await supabase
        .from('ai_tools')
        .update({ embedding })
        .eq('id', toolId)

    if (updateError) {
        logger.error("[Embeddings] Error updating embedding:", updateError)
        return false
    }

    logger.info(`[Embeddings] Updated embedding for: ${tool.name}`)
    return true
}

/**
 * Check if semantic search is available (migration has been run)
 * Cached for 5 minutes to avoid checking on every request.
 */
let semanticAvailableCache: { value: boolean, timestamp: number } | null = null
const SEMANTIC_CHECK_TTL = 1000 * 60 * 5 // 5 minutes

export async function isSemanticSearchAvailable(): Promise<boolean> {
    // Return cached result if fresh
    if (semanticAvailableCache && (Date.now() - semanticAvailableCache.timestamp < SEMANTIC_CHECK_TTL)) {
        return semanticAvailableCache.value
    }

    const supabase = getSupabaseAdmin()

    try {
        // Check if the embedding column exists
        const { data, error } = await supabase
            .from('ai_tools')
            .select('embedding')
            .limit(1)

        if (error) {
            semanticAvailableCache = { value: false, timestamp: Date.now() }
            return false
        }

        semanticAvailableCache = { value: true, timestamp: Date.now() }
        return true
    } catch {
        semanticAvailableCache = { value: false, timestamp: Date.now() }
        return false
    }
}