-- ============================================================================
-- Reclaim storage: drop two large GIN trigram indexes that nothing uses and
-- that were measured as not viable even when they were used.
--
-- WHY THESE ARE DEAD
--
-- docs/CORPUS_AND_CONSTRAINTS.md §2 measured ILIKE against this table WITH
-- these indexes in place:
--
--     FTS  (fts_vector @@ tsquery)      421ms - 1.5s   viable
--     ILIKE on name (trigram indexed)   8.5s           not viable
--     ILIKE on description (indexed)    TIMEOUT        not viable
--
-- so search was moved to full-text over ai_tools_fts_idx. Every remaining
-- ILIKE-on-ai_tools code path is now unreachable:
--
--   * lib/services/tools.service.ts  - the whole ToolsService class has no
--     callers (removed in this change)
--   * lib/search-utils.ts buildSearchConditions() - no callers (removed in
--     this change)
--
-- Live search runs textSearch('fts_vector', ...) in app/api/ai-models/route.ts
-- and lib/retrieval.ts. Neither touches a trigram index.
--
-- WHY IT MATTERS FOR STORAGE
--
-- A GIN trigram index over ~260k descriptions of ~200 characters each is one
-- of the largest objects in this database -- trigram GIN typically runs 2-4x
-- the size of the indexed text. This is storage spent on a query shape we
-- have measured as unusable and no longer issue.
--
-- CHECK BEFORE YOU RUN THIS. Both numbers should confirm the story: a large
-- size, and idx_scan at or near zero.
--
--     SELECT indexrelname,
--            pg_size_pretty(pg_relation_size(indexrelid)) AS size,
--            idx_scan
--       FROM pg_stat_user_indexes
--      WHERE relname = 'ai_tools'
--      ORDER BY pg_relation_size(indexrelid) DESC;
--
-- Note that idx_scan counts since the last stats reset, not since creation.
-- If it is non-zero, find the caller before dropping.
--
-- REVERSIBLE, but not cheaply: rebuilding a GIN trigram index over 260k rows
-- is a long, write-heavy operation that will churn the table. The recreate
-- statements are at the bottom, commented out.
-- ============================================================================

DROP INDEX IF EXISTS idx_ai_tools_description_trgm;
DROP INDEX IF EXISTS idx_ai_tools_name_trgm;

-- idx_ai_tools_platform_trgm is deliberately KEPT. Unlike the two above it is
-- over a short URL column rather than prose, so it is small, and
-- fix_advanced_search_bounded_retrieval.sql created it for the platform
-- matching inside search_tools_advanced -- which is live.

-- Planner statistics do not depend on dropped indexes, but the table's plans
-- do. Re-analyze so the planner re-costs every query that could previously
-- have considered these.
ANALYZE ai_tools;

-- ----------------------------------------------------------------------------
-- Rollback, if a trigram path is ever genuinely needed again. Prefer adding
-- the term to fts_vector instead -- that index already exists and is fast.
--
-- CREATE EXTENSION IF NOT EXISTS pg_trgm;
-- CREATE INDEX idx_ai_tools_name_trgm
--   ON ai_tools USING gin (name gin_trgm_ops);
-- CREATE INDEX idx_ai_tools_description_trgm
--   ON ai_tools USING gin (description gin_trgm_ops);
-- ----------------------------------------------------------------------------
